/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=ofProperty_9a34666daa
ROOST_METHOD_SIG_HASH=ofProperty_66d224beda

"""
Scenario 1: Valid Property through String
TestName: testOfPropertyWithValidString.
Description: This test checks if the method can correctly create a VersionReference instance and assign a version property when provided with a valid input string.
Execution:
  Arrange: An input string representing a valid internal property is identified and noted.
  Act: The ofProperty method from VersionReference class is invoked using this input string.
  Assert: Check if the created VersionReference instance is not null, getProperty method of the created VersionReference instance returns a property that matches the input string.
Validation:
  This test confirms that the method correctly assigns the provided property value when input string matches the internal property. This is essential for maintaining data consistency and expected behavior of the Software version reference framework.

Scenario 2: Null Input String
TestName: testOfPropertyWithNullString.
Description: This test checks how the method handles a null string input as a property.
Execution:
  Arrange: A null input is noted.
  Act: The ofProperty method from VersionReference class is invoked using this null input.
  Assert: A NullPointerException is expected to be thrown.
Validation:
  This test validates that the method throws an appropriate exception when null is passed. Proper handling of null inputs is crucial to avoid runtime errors and ensure stability of the application.

Scenario 3: Empty Input String
TestName: testOfPropertyWithEmptyString.
Description: This test checks how the method responds to an empty string input as a property.
Execution:
  Arrange: An empty string "" as input is noted.
  Act: The ofProperty method from VersionReference class is invoked using this empty string.
  Assert: Check if the created VersionReference instance is not null, getProperty method of the created VersionReference instance returns an empty VersionProperty.
Validation:
  This test validates that the method creates an instance with an empty property when an empty string is passed. This is important for maintaining correctness in scenarios where empty properties are allowed.

Scenario 4: Property Not Found
TestName: testOfPropertyWithNonExistentProperty.
Description: This test verifies if the method can gracefully handle scenarios where the input string does not correspond to a known internal property.
Execution:
  Arrange: A string representing a non-existent property is identified and noted.
  Act: The ofProperty method from VersionReference class is invoked using this non-existent property string.
  Assert: Check if the created VersionReference instance is not null, getProperty method of the created VersionReference instance returns null or throws an exception.
Validation:
  This test ensures that the method handles non-existent properties gracefully either by accepting it and returning null or by throwing an exception. This behavior is consistent with the method signature which allows null values and ensures that the method does not break when a non-existent property is passed.
"""
*/

// ********RoostGPT********

package io.spring.initializr.generator.version;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.*;
import java.util.Objects;

public class VersionReferenceOfProperty854Test {

	@Test
	@Tag("valid")
	public void testOfPropertyWithValidString() {
		// Arrange
		String property = "property";
		// Act
		VersionReference versionReference = VersionReference.ofProperty(property);
		// Assert
		assertNotNull(versionReference);
		assertEquals(VersionProperty.of(property), versionReference.getProperty());
	}

	@Test
	@Tag("invalid")
	public void testOfPropertyWithNullString() {
		// Arrange
		String property = null;
		// Act and Assert
		assertThrows(NullPointerException.class, () -> VersionReference.ofProperty(property));
	}

	@Test
	@Tag("boundary")
	public void testOfPropertyWithEmptyString() {
		// Arrange
		String property = "";
		// Act
		VersionReference versionReference = VersionReference.ofProperty(property);
		// Assert
		assertNotNull(versionReference);
		assertEquals(VersionProperty.of(property), versionReference.getProperty());
	}

	@Test
	@Tag("invalid")
	public void testOfPropertyWithNonExistentProperty() {
		// Arrange
		String property = "nonExistentProperty";
		// Act
		VersionReference versionReference = VersionReference.ofProperty(property);
		// Assert
		assertNotNull(versionReference);
		assertEquals(null, versionReference.getProperty());
	}

}