/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_7d727705e8
ROOST_METHOD_SIG_HASH=add_81350939a4

Scenario 1: Valid Invocation Adds Extension to Map

Details:
  TestName: validInvocationAddsExtensionToMap
  Description: Ensures that invoking the `add(String groupId, String artifactId, Consumer<MavenExtension.Builder> extension)` method adds an extension to the `extensions` map with the appropriate key and value.

Execution:
  Arrange:
    Prepare a `MavenExtensionContainer` instance and a valid `groupId`, `artifactId`, and a `Consumer<MavenExtension.Builder>` instance.

  Act:
    Call the `add` method using the prepared parameters.

  Assert:
    Verify that the `extensions` map now contains an entry where the key matches the concatenation of `groupId:artifactId` and the corresponding value is a properly configured `MavenExtension.Builder` instance.

Validation:
  Ensures that the method correctly modifies the internal state of the object (`extensions` map) as expected when valid inputs are provided. Verifies the functionality that the `add` method provides, which is critical for adding extensions to the system.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem.maven;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import java.util.function.Consumer;
import org.junit.jupiter.api.*;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.stream.Stream;

public class MavenExtensionContainerAdd703Test {

	@Test
	@Tag("valid")
	public void validInvocationAddsExtensionToMap() {
		// Arrange
		MavenExtensionContainer container = new MavenExtensionContainer();
		String groupId = "org.springframework"; // TODO: Update with realistic value if
												// needed
		String artifactId = "spring-core"; // TODO: Update with realistic value if needed
		Consumer<MavenExtension.Builder> mockConsumer = Mockito.mock(Consumer.class);

		// Act
		container.add(groupId, artifactId, mockConsumer);
		// Assert
		Mockito.verify(mockConsumer).accept(Mockito.any(MavenExtension.Builder.class));
	}

}