/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_564526ef0a
ROOST_METHOD_SIG_HASH=add_33814f52a7


Scenario 1: Adding a Maven plugin with groupId and artifactId parameters

Details:
  TestName: addPluginWithGroupIdAndArtifactId
  Description: Verify that the add method successfully adds a plugin to the `plugins` map when called with `groupId` and `artifactId` parameters.

Execution:
  Arrange: Initialize a MavenPluginContainer instance and define a groupId and artifactId.
  Act: Call the `add` method with the provided `groupId` and `artifactId` parameters.
  Assert: Verify that the `plugins` map contains an entry with the expected key and a corresponding `MavenPlugin.Builder` value.

Validation:
  Ensure the `plugins` map accurately reflects the addition of a new plugin using the specified `groupId` and `artifactId`. Confirm that this behavior aligns with the application’s expected functionality for plugin management.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem.maven;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import java.util.function.Consumer;
import org.junit.jupiter.api.*;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.stream.Stream;
import io.spring.initializr.generator.buildsystem.maven.MavenPlugin.Builder;

public class MavenPluginContainerAdd827Test {

	@Test
	@Tag("valid")
	public void addPluginWithValidGroupIdAndArtifactId() {
		// Arrange
		MavenPluginContainer container = new MavenPluginContainer();
		String groupId = "org.springframework"; // TODO: Replace with desired groupId
		String artifactId = "spring-plugin"; // TODO: Replace with desired artifactId
		Consumer<MavenPlugin.Builder> pluginConsumer = Mockito.mock(Consumer.class);
		// Act
		container.add(groupId, artifactId, pluginConsumer);
		// Assert
		Mockito.verify(pluginConsumer).accept(Mockito.any(MavenPlugin.Builder.class));
	}

	@Test
	@Tag("invalid")
	public void addPluginWithNullGroupId() {
		// Arrange
		MavenPluginContainer container = new MavenPluginContainer();
		String groupId = null; // Invalid groupId
		String artifactId = "spring-plugin"; // TODO: Replace with desired artifactId
		Consumer<MavenPlugin.Builder> pluginConsumer = Mockito.mock(Consumer.class);
		// Act & Assert
		try {
			container.add(groupId, artifactId, pluginConsumer);
		}
		catch (NullPointerException e) {
			// Assert
			assert e.getMessage() != null;
		}
	}

	@Test
	@Tag("invalid")
	public void addPluginWithEmptyGroupId() {
		// Arrange
		MavenPluginContainer container = new MavenPluginContainer();
		String groupId = ""; // Invalid groupId
		String artifactId = "spring-plugin"; // TODO: Replace with desired artifactId
		Consumer<MavenPlugin.Builder> pluginConsumer = Mockito.mock(Consumer.class);
		// Act & Assert
		try {
			container.add(groupId, artifactId, pluginConsumer);
		}
		catch (IllegalArgumentException e) {
			// Assert
			assert e.getMessage() != null;
		}
	}

	@Test
	@Tag("boundary")
	public void addPluginWithBoundaryLengthGroupIdAndArtifactId() {
		// Arrange
		MavenPluginContainer container = new MavenPluginContainer();
		String groupId = "o".repeat(255); // Boundary edge value
		String artifactId = "a".repeat(255); // Boundary edge value
		Consumer<MavenPlugin.Builder> pluginConsumer = Mockito.mock(Consumer.class);
		// Act
		container.add(groupId, artifactId, pluginConsumer);
		// Assert
		Mockito.verify(pluginConsumer).accept(Mockito.any(MavenPlugin.Builder.class));
	}

	@Test
	@Tag("valid")
	public void addPluginConsumerWorksCorrectlyWithValidInputs() {
		// Arrange
		MavenPluginContainer container = new MavenPluginContainer();
		String groupId = "com.samskivert"; // TODO: Replace with desired groupId
		String artifactId = "artifact-core"; // TODO: Replace with desired artifactId
		Consumer<MavenPlugin.Builder> pluginConsumer = builder -> {
			assert builder != null;
		};
		// Act
		container.add(groupId, artifactId, pluginConsumer);
		// Assert
		// The consumer assertion itself validates correctness.
	}

	@Test
	@Tag("valid")
	public void addPluginConsumerHandlesLargeInputs() {
		// Arrange
		MavenPluginContainer container = new MavenPluginContainer();
		String groupId = "g".repeat(500); // Large input value
		String artifactId = "a".repeat(500); // Large input value
		Consumer<MavenPlugin.Builder> pluginConsumer = Mockito.mock(Consumer.class);
		// Act
		container.add(groupId, artifactId, pluginConsumer);
		// Assert
		Mockito.verify(pluginConsumer).accept(Mockito.any(MavenPlugin.Builder.class));
	}

}