/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_fe01e1d3a6
ROOST_METHOD_SIG_HASH=add_a63c55035e


Scenario [1]: Verify add method adds a new resource if the directory does not exist

Details:
  TestName: addResourceForNewDirectory
  Description: This test case verifies that when the `add` method is called with a directory name that does not exist in the `resources` map, it correctly adds a new `MavenResource.Builder` object.

Execution:
  Arrange: Create an instance of `MavenResourceContainer`. Use a directory name that is not present in the `resources` map. Provide a dummy `Consumer` object that performs no operation.
  Act: Call the `add` method with the directory name and dummy `Consumer`.
  Assert: Verify that the `resources` map contains the new directory and its value corresponds to a `MavenResource.Builder` object created using the directory name.

Validation:
  This validates the correct functionality of the `computeIfAbsent` logic in adding a new resource for a non-existent directory. Ensures the method adheres to the intended business logic of maintaining resource mappings.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem.maven;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Consumer;
import static org.assertj.core.api.Assertions.assertThat;
import org.junit.jupiter.api.*;
import java.util.stream.Stream;

public class MavenResourceContainerAdd416Test {

	private static class MavenResource {

		public static class Builder {

			private final String directory;

			public Builder(String directory) {
				this.directory = directory; // TODO: Modify `directory` values during
											// actual tests as required.
			}

		}

	}

	private static class MavenResourceContainer {

		private final Map<String, MavenResource.Builder> resources = new LinkedHashMap<>();

		public void add(String directory) {
			this.resources.computeIfAbsent(directory, (key) -> new MavenResource.Builder(directory));
		}

		public void add(String directory, Consumer<MavenResource.Builder> resource) {
			resource.accept(this.resources.computeIfAbsent(directory, (key) -> new MavenResource.Builder(directory)));
		}

	}

	@Test
	@Tag("valid")
	public void addResourceForNewDirectory() {
		// Arrange
		MavenResourceContainer container = new MavenResourceContainer();
		String newDirectory = "resources/new-folder"; // TODO: Change directory to new
														// paths during edge case testing.
		Consumer<MavenResource.Builder> dummyResourceConsumer = Mockito.mock(Consumer.class);
		// Act
		container.add(newDirectory, dummyResourceConsumer);
		// Assert
		assertThat(container.resources.containsKey(newDirectory)).isTrue();
		assertThat(container.resources.get(newDirectory)).isInstanceOf(MavenResource.Builder.class);
		Mockito.verify(dummyResourceConsumer).accept(Mockito.any(MavenResource.Builder.class));
	}

	@Test
	@Tag("invalid")
	public void addResourceForExistingDirectory() {
		// Arrange
		MavenResourceContainer container = new MavenResourceContainer();
		String existingDirectory = "resources/existing-folder"; // TODO: Change directory
																// path during specific
																// tests if needed.
		container.add(existingDirectory); // Pre-populate resources with an existing
											// directory.
		Consumer<MavenResource.Builder> dummyResourceConsumer = Mockito.mock(Consumer.class);
		// Act
		container.add(existingDirectory, dummyResourceConsumer);
		// Assert
		assertThat(container.resources.containsKey(existingDirectory)).isTrue();
		assertThat(container.resources.get(existingDirectory)).isInstanceOf(MavenResource.Builder.class);
		Mockito.verify(dummyResourceConsumer).accept(Mockito.any(MavenResource.Builder.class));
	}

	@Test
	@Tag("boundary")
	public void addResourceForNullDirectory() {
		// Arrange
		MavenResourceContainer container = new MavenResourceContainer();
		Consumer<MavenResource.Builder> dummyResourceConsumer = Mockito.mock(Consumer.class);
		// Act + Assert
		assertThatThrownBy(() -> container.add(null, dummyResourceConsumer)).isInstanceOf(NullPointerException.class); // Validate
																														// proper
																														// exception
																														// handling.
	}

	@Test
	@Tag("integration")
	public void addResourceWithCustomConsumer() {
		// Arrange
		MavenResourceContainer container = new MavenResourceContainer();
		String directory = "resources/integration-folder"; // TODO: Keep directory dynamic
															// for additional testing.
		Consumer<MavenResource.Builder> customConsumer = (builder) -> System.out.println("Executing custom consumer!");
		// Act
		container.add(directory, customConsumer);
		// Assert
		assertThat(container.resources.containsKey(directory)).isTrue();
		assertThat(container.resources.get(directory)).isInstanceOf(MavenResource.Builder.class);
	}

}