/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_5efe6693b4
ROOST_METHOD_SIG_HASH=add_5abda0cacf


Scenario [1]: Verify that `add` correctly adds an extension when valid `groupId`, `artifactId`, and `version` are provided.

Details:
  TestName: addExtensionSuccessfullyWithValidInputs
  Description: Ensures that the extension is added to the `extensions` map with the correctly populated properties when valid `groupId`, `artifactId`, and `version` strings are supplied.

Execution:
  Arrange: Initialize the `MavenExtensionContainer` object and prepare valid `groupId`, `artifactId`, and `version` strings.
  Act: Invoke the `add` method with the valid arguments.
  Assert: Check if the `extensions` map contains an entry with a key derived from `groupId:artifactId` and verify the version.

Validation:
  This test validates whether the method correctly adds the extension and stores it in the `extensions` map. By checking the version, the test verifies that the logic within the consumer correctly modifies the properties for the extension.

---

Scenario [2]: Verify that calling `add` multiple times with the same `groupId` and `artifactId` updates the extension with the latest version.

Details:
  TestName: updateExistingExtensionWithLatestVersion
  Description: Verifies that an existing entry in `extensions` is updated with the most recent version provided when the `add` method is called with the same `groupId` and `artifactId`.

Execution:
  Arrange: Initialize the `MavenExtensionContainer` object and add an extension with certain `groupId`, `artifactId`, and `version`. Prepare a second version for the same `groupId` and `artifactId`.
  Act: Invoke the `add` method with the same `groupId` and `artifactId` but a new version.
  Assert: Check if the version of the entry in the `extensions` map matches the latest version provided.

Validation:
  This test ensures that the `add` method correctly updates existing extensions when the same `groupId` and `artifactId` are supplied. It verifies proper behavior for updates.

---

Scenario [3]: Verify behavior when `add` is called with `null` values for `groupId`.

Details:
  TestName: addExtensionWithNullGroupId
  Description: Ensures the method handles a `groupId` of `null` gracefully, whether or not exceptions are thrown as designed.

Execution:
  Arrange: Initialize the `MavenExtensionContainer` object and provide `null` for `groupId`, along with valid `artifactId` and `version`.
  Act: Invoke the `add` method with these values.
  Assert: Assert if either an exception is thrown or if the key construction and map operation are performed differently.

Validation:
  This test validates whether the method is resilient against null values for `groupId`. Exception handling or alternate behavior is expected per design.

---

Scenario [4]: Verify behavior when `add` is called with `null` values for `artifactId`.

Details:
  TestName: addExtensionWithNullArtifactId
  Description: Ensures the method handles a `null` value for `artifactId` gracefully, whether or not exceptions are thrown as designed.

Execution:
  Arrange: Initialize the `MavenExtensionContainer` object and provide valid `groupId` and `version`, but `null` for `artifactId`.
  Act: Invoke the `add` method with these values.
  Assert: Assert if either an exception is thrown or if the key construction and map operation are performed differently.

Validation:
  This test evaluates the behavior of the method when `artifactId` is `null`. Exception handling or alternate behavior verification is essential.

---

Scenario [5]: Verify behavior when `add` is called with `null` values for `version`.

Details:
  TestName: addExtensionWithNullVersion
  Description: Ensures the method handles a `null` value for `version` gracefully, whether or not exceptions or fallback values are used as designed.

Execution:
  Arrange: Initialize the `MavenExtensionContainer` object and provide valid `groupId` and `artifactId`, but `null` for `version`.
  Act: Invoke the `add` method with these values.
  Assert: Check if the `extensions` map contains a key corresponding to `groupId:artifactId`, and verify whether a `null` version is acceptable or throws an exception.

Validation:
  This test ensures that the `add` method correctly handles the absence of a version. It evaluates resilience and exception handling or fallback logic.

---

Scenario [6]: Verify that the `add` method successfully invokes the inner `Consumer` logic.

Details:
  TestName: ensureConsumerLogicIsInvoked
  Description: This test checks that the inner consumer defined in the overloaded `add` method successfully executes and modifies the extension builder properties.

Execution:
  Arrange: Initialize the `MavenExtensionContainer` object and supply valid `groupId`, `artifactId`, and `version` to the `add` method.
  Act: Invoke the `add` method.
  Assert: Inspect the state of the builder within the `extensions` map to ensure that the version has been correctly applied.

Validation:
  This test validates the correct execution of the nested consumer logic as part of the core functionality. It ensures that modifications are made accurately within the `addExtension` invocation.

---

Scenario [7]: Verify the `extensions` map remains empty when an exception is thrown during method execution.

Details:
  TestName: ensureExtensionsMapEmptyOnException
  Description: This test checks whether the `extensions` map remains unmodified if an exception is thrown during the `add` method's execution.

Execution:
  Arrange: Initialize the `MavenExtensionContainer` object, and deliberately supply invalid or problematic values to trigger an exception.
  Act: Invoke the `add` method.
  Assert: Verify that the `extensions` map remains empty.

Validation:
  This test ensures the integrity of the `extensions` map when an error is encountered in the `add` method. It verifies that no entries are partially or incorrectly added.


*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem.maven;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Consumer;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import java.util.stream.Stream;

class MavenExtensionContainerAddTest {

	class MavenExtensionContainer {

		Map<String, MavenExtension.Builder> extensions = new LinkedHashMap<>();

		public void add(String groupId, String artifactId, String version) {
			add(groupId, artifactId, (extension) -> extension.version(version));
		}

		public void add(String groupId, String artifactId, Consumer<MavenExtension.Builder> extensionConsumer) {
			extensionConsumer.accept(addExtension(groupId, artifactId));
		}

		private MavenExtension.Builder addExtension(String groupId, String artifactId) {
			String key = groupId + ":" + artifactId;
			MavenExtension.Builder builder = new MavenExtension.Builder();
			extensions.put(key, builder);
			return builder;
		}

	}

	class MavenExtension {

		static class Builder {

			private String version;

			public void version(String version) {
				this.version = version;
			}

			public String getVersion() {
				return version;
			}

		}

	}

	@Test
	@Tag("valid")
	public void addExtensionSuccessfullyWithValidInputs() {
		MavenExtensionContainer container = new MavenExtensionContainer();
		String groupId = "org.springframework"; // TODO: Replace with valid groupId
		String artifactId = "spring-context"; // TODO: Replace with valid artifactId
		String version = "5.3.0"; // TODO: Replace with valid version
		container.add(groupId, artifactId, version);
		MavenExtension.Builder addedExtension = container.extensions.get(groupId + ":" + artifactId);
		assertEquals(version, addedExtension.getVersion(), "Version should match the provided input");
	}

	@Test
	@Tag("valid")
	public void updateExistingExtensionWithLatestVersion() {
		MavenExtensionContainer container = new MavenExtensionContainer();
		String groupId = "org.springframework";
		String artifactId = "spring-context";
		String initialVersion = "5.3.0"; // TODO: Replace with valid version
		String updatedVersion = "5.3.1"; // TODO: Replace with valid version
		container.add(groupId, artifactId, initialVersion);
		container.add(groupId, artifactId, updatedVersion);
		MavenExtension.Builder updatedExtension = container.extensions.get(groupId + ":" + artifactId);
		assertEquals(updatedVersion, updatedExtension.getVersion(),
				"Version should be updated to the latest provided value");
	}

	@Test
	@Tag("invalid")
	public void addExtensionWithNullGroupId() {
		MavenExtensionContainer container = new MavenExtensionContainer();
		String groupId = null;
		String artifactId = "spring-context"; // TODO: Replace with valid artifactId
		String version = "5.3.0"; // TODO: Replace with valid version
		assertThrows(NullPointerException.class, () -> container.add(groupId, artifactId, version),
				"Method should throw exception when groupId is null");
	}

	@Test
	@Tag("invalid")
	public void addExtensionWithNullArtifactId() {
		MavenExtensionContainer container = new MavenExtensionContainer();
		String groupId = "org.springframework"; // TODO: Replace with valid groupId
		String artifactId = null;
		String version = "5.3.0"; // TODO: Replace with valid version
		assertThrows(NullPointerException.class, () -> container.add(groupId, artifactId, version),
				"Method should throw exception when artifactId is null");
	}

	@Test
	@Tag("invalid")
	public void addExtensionWithNullVersion() {
		MavenExtensionContainer container = new MavenExtensionContainer();
		String groupId = "org.springframework"; // TODO: Replace with valid groupId
		String artifactId = "spring-context"; // TODO: Replace with valid artifactId
		String version = null;
		container.add(groupId, artifactId, version);
		MavenExtension.Builder addedExtension = container.extensions.get(groupId + ":" + artifactId);
		assertNull(addedExtension.getVersion(), "Version should be null when a null value is provided");
	}

	@Test
	@Tag("integration")
	public void ensureConsumerLogicIsInvoked() {
		MavenExtensionContainer container = new MavenExtensionContainer();
		String groupId = "org.springframework"; // TODO: Replace with valid groupId
		String artifactId = "spring-context"; // TODO: Replace with valid artifactId
		String version = "5.3.0"; // TODO: Replace with valid version
		container.add(groupId, artifactId, version);
		MavenExtension.Builder addedExtension = container.extensions.get(groupId + ":" + artifactId);
		assertEquals(version, addedExtension.getVersion(), "Consumer should apply version correctly");
	}

	@Test
	@Tag("boundary")
	public void ensureExtensionsMapEmptyOnException() {
		MavenExtensionContainer container = spy(new MavenExtensionContainer());
		String groupId = "org.springframework"; // TODO: Replace with valid groupId
		String artifactId = "spring-context"; // TODO: Replace with valid artifactId
		String version = "5.3.0"; // TODO: Replace with valid version
		doThrow(RuntimeException.class).when(container)
			.add(groupId, artifactId, (Consumer<MavenExtension.Builder>) any());
		assertThrows(RuntimeException.class, () -> container.add(groupId, artifactId, version));
		assertTrue(container.extensions.isEmpty(), "Extensions map should remain empty on exception");
	}

}