/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_7d727705e8
ROOST_METHOD_SIG_HASH=add_81350939a4

Scenario 1: Valid Invocation Adds Extension to Map

Details:
  TestName: validInvocationAddsExtensionToMap
  Description: Ensures that invoking the `add(String groupId, String artifactId, Consumer<MavenExtension.Builder> extension)` method adds an extension to the `extensions` map with the appropriate key and value.

Execution:
  Arrange:
    Prepare a `MavenExtensionContainer` instance and a valid `groupId`, `artifactId`, and a `Consumer<MavenExtension.Builder>` instance.

  Act:
    Call the `add` method using the prepared parameters.

  Assert:
    Verify that the `extensions` map now contains an entry where the key matches the concatenation of `groupId:artifactId` and the corresponding value is a properly configured `MavenExtension.Builder` instance.

Validation:
  Ensures that the method correctly modifies the internal state of the object (`extensions` map) as expected when valid inputs are provided. Verifies the functionality that the `add` method provides, which is critical for adding extensions to the system.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem.maven;

import org.junit.jupiter.api.*;
import org.mockito.Mockito;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Consumer;
import static org.assertj.core.api.Assertions.*;
import java.util.stream.Stream;

@Tag("integration")
public class MavenExtensionContainerAdd33Test {

	@Mock
	MavenExtension.Builder mockBuilder;

	@InjectMocks
	MavenExtensionContainer mavenExtensionContainer;

	private Map<String, MavenExtension.Builder> extensions;

	@BeforeEach
	public void setup() {
		MockitoAnnotations.openMocks(this);
		extensions = new LinkedHashMap<>();
	}

	@Test
	@Tag("valid")
	public void validInvocationAddsExtensionToMap() {
		// Arrange
		String groupId = "com.example"; // TODO: Update as needed
		String artifactId = "my-artifact"; // TODO: Update as needed
		Consumer<MavenExtension.Builder> extension = builder -> builder.version("1.0.0"); // TODO:
																							// Update
																							// as
																							// needed
		Mockito.doAnswer(invocation -> {
			extensions.put(groupId + ":" + artifactId, mockBuilder);
			return null;
		}).when(mockBuilder).version(Mockito.anyString());
		// Act
		mavenExtensionContainer.add(groupId, artifactId, extension);
		// Assert
		assertThat(extensions).containsKey(groupId + ":" + artifactId);
		assertThat(extensions.get(groupId + ":" + artifactId)).isInstanceOf(MavenExtension.Builder.class);
	}

}