/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_5efe6693b4
ROOST_METHOD_SIG_HASH=add_5abda0cacf

Scenario [1]: Verify the correct addition of an extension with valid groupId, artifactId, and version.

Details:
  TestName: addExtensionWithValidInputs
  Description: This test verifies if the `add` method correctly adds an extension to the `extensions` map given valid inputs for `groupId`, `artifactId`, and `version`. It ensures that the extension's `version` attribute is set appropriately.

Execution:
  Arrange: Initialize an instance of `MavenExtensionContainer`. Prepare valid values for `groupId`, `artifactId`, and `version`.
  Act: Call the `add` method with the specified values.
  Assert: Check that the `extensions` map contains the correct key (`groupId` + ":" + `artifactId`) and that the mapped value represents the expected `MavenExtension.Builder` with the correct `version` attribute.

Validation:
  Verify that the correct extension is added to the `extensions` map with the expected version, as this reflects proper functionality of the `add` method. Valid data inputs should lead to predictable and correct additions to the `extensions` map.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem.maven;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Consumer;
import static org.assertj.core.api.Assertions.assertThat;
import org.junit.jupiter.api.*;
import java.util.stream.Stream;

public class MavenExtensionContainerAddTest {

	@Test
	@Tag("valid")
	public void addExtensionWithValidInputs() {
		// Arrange
		MavenExtensionContainer container = new MavenExtensionContainer();
		String groupId = "org.springframework"; // TODO: Change to desired value
		String artifactId = "spring-framework"; // TODO: Change to desired value
		String version = "5.2.0"; // TODO: Change to desired value
		// Act
		container.add(groupId, artifactId, version);
		// Assert
		MavenExtension.Builder actualExtension = container.getExtensions().get(groupId + ":" + artifactId);
		assertThat(actualExtension).isNotNull();
		assertThat(actualExtension.getVersion()).isEqualTo(version);
	}

	// Helper class for mocking and testing
	public static class MavenExtensionContainer {

		private final Map<String, MavenExtension.Builder> extensions = new LinkedHashMap<>();

		public void add(String groupId, String artifactId, String version) {
			add(groupId, artifactId, (extension) -> extension.version(version));
		}

		public void add(String groupId, String artifactId, Consumer<MavenExtension.Builder> extension) {
			extension.accept(addExtension(groupId, artifactId));
		}

		public MavenExtension.Builder addExtension(String groupId, String artifactId) {
			MavenExtension.Builder extension = Mockito.mock(MavenExtension.Builder.class);
			extensions.put(groupId + ":" + artifactId, extension);
			return extension;
		}

		public Map<String, MavenExtension.Builder> getExtensions() {
			return extensions;
		}

	}

	// Helper class to simulate MavenExtension.Builder
	public static class MavenExtension {

		public static class Builder {

			private String version;

			public Builder version(String version) {
				this.version = version;
				return this;
			}

			public String getVersion() {
				return version;
			}

		}

	}

}