/*
 * Copyright 2012-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_548af2ab1c
ROOST_METHOD_SIG_HASH=add_2d115f89b3


Scenario [1]: Verify correct execution when valid `id` and `builder` are provided

Details:
  TestName: addValidIdAndBuilder
  Description: This test validates that the `add` method successfully adds a BillOfMaterials instance when provided with a valid `id` and `BillOfMaterials.Builder`.

Execution:
  Arrange: Create a valid `id` string and an instance of `BillOfMaterials.Builder`. Use the `builder.build()` method to construct the BillOfMaterials object before invoking the `add` method.
  Act: Pass the `id` and `builder` to the `add` method.
  Assert: Check that the expected `BillOfMaterials` object associated with the given `id` is correctly added.
Validation:
  This test ensures the core functionality of the `add` method works as expected when valid inputs are passed. It verifies proper storage of the generated BillOfMaterials instance.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.Mockito;
import org.assertj.core.api.Assertions;
import java.util.function.Function;
import java.util.LinkedHashMap;
import org.junit.jupiter.api.*;

public class BomContainerAddTest {

	private BomContainer bomContainer;

	private Function<String, BillOfMaterials> mockItemResolver;

	@BeforeEach
	public void setUp() {
		mockItemResolver = Mockito.mock(Function.class);
		bomContainer = new BomContainer(mockItemResolver);
	}

	@Test
	@Tag("valid")
	public void addValidIdAndBuilder() {
		// Arrange
		String id = "test-id"; // TODO: Replace with specific id values if needed
		BillOfMaterials.Builder builder = new BillOfMaterials.Builder();
		BillOfMaterials expectedBillOfMaterials = builder.build();
		// Act
		bomContainer.add(id, builder);
		// Assert
		Assertions.assertThat(((BillOfMaterials) (mockItemResolver.apply(id)))) // Type-casting
																				// the
																				// resolved
																				// item
			.isNotNull()
			.isEqualTo(expectedBillOfMaterials);
	}

}