/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=onlySnapshots_e99a253849
ROOST_METHOD_SIG_HASH=onlySnapshots_421e4ff951

Scenario 1: Verify onlySnapshots enables snapshots and disables releases

Details:
  TestName: onlySnapshotsEnablesSnapshotsAndDisablesReleases
  Description: This test checks the method `onlySnapshots` to ensure that it sets the `snapshotsEnabled` field to true and the `releasesEnabled` field to false.
Execution:
  Arrange: Create an instance of the `Builder` class.
  Act: Invoke the `onlySnapshots` method on the `Builder` instance.
  Assert: Validate that `snapshotsEnabled` is true and `releasesEnabled` is false by chaining the method calls.
Validation:
  This assertion verifies that the `onlySnapshots` method correctly modifies the state of `Builder` to ensure it only supports snapshots, as intended.

Scenario 2: Verify onlySnapshots method chaining consistency

Details:
  TestName: methodChainingConsistencyWithOnlySnapshots
  Description: This test ensures that the `onlySnapshots` method operates as part of a consistent method chain, returning the same `Builder` instance it was invoked on.
Execution:
  Arrange: Create an instance of the `Builder` class and store a reference to it.
  Act: Invoke the `onlySnapshots` method and capture the returned instance.
  Assert: Compare the original instance with the returned instance to ensure they are identical.
Validation:
  This test checks that `onlySnapshots` adheres to the builder pattern by returning the same instance, enabling further chaining of method calls.

Scenario 3: Verify id field behavior remains unaffected by onlySnapshots usage

Details:
  TestName: onlySnapshotsDoesNotAlterIdField
  Description: This test validates that the `onlySnapshots` method does not unintentionally modify unrelated fields like `id`.
Execution:
  Arrange: Create an instance of `Builder` and set the `id` to a specific value using the `id` method.
  Act: Invoke the `onlySnapshots` method on the `Builder` instance.
  Assert: Ensure that the `id` field remains unchanged after the method call.
Validation:
  Ensures the `onlySnapshots` method does not introduce any unintended side effects on unrelated fields.

Scenario 4: Verify name field behavior remains unchanged by onlySnapshots usage

Details:
  TestName: onlySnapshotsDoesNotAlterNameField
  Description: This test ensures that the `onlySnapshots` method does not inadvertently modify the `name` field in the `Builder` instance.
Execution:
  Arrange: Create an instance of `Builder` and set the `name` using the `name` method.
  Act: Call the `onlySnapshots` method on the `Builder` instance.
  Assert: Validate that the `name` field retains its original assigned value.
Validation:
  Confirms that the `onlySnapshots` method makes no changes to the `name` field and behaves as expected.

Scenario 5: Verify url field behavior remains unaffected by onlySnapshots usage

Details:
  TestName: onlySnapshotsDoesNotAlterUrlField
  Description: This test ensures the `onlySnapshots` method does not modify the `url` field in the `Builder` instance.
Execution:
  Arrange: Create a `Builder` object and set the `url` to a known value using the `url` method.
  Act: Invoke the `onlySnapshots` method on the `Builder` instance.
  Assert: Confirm that the `url` field remains unchanged after the method call.
Validation:
  This test ensures that the `onlySnapshots` method does not affect any unrelated fields, such as `url`.

Scenario 6: Verify build method's output after invoking onlySnapshots

Details:
  TestName: buildMethodReflectsOnlySnapshotsChanges
  Description: This test ensures that invoking the `build` method after calling `onlySnapshots` creates a `MavenRepository` instance with proper `snapshotsEnabled` and `releasesEnabled` values.
Execution:
  Arrange: Create an instance of `Builder` and call the `onlySnapshots` method.
  Act: Invoke the `build` method and retrieve a `MavenRepository` instance.
  Assert: Validate that the `MavenRepository` instance has `snapshotsEnabled` set to true and `releasesEnabled` set to false.
Validation:
  Confirms that the builder's final state appropriately propagates to the constructed `MavenRepository` instance.

Scenario 7: Verify onlySnapshots method interaction with releasesEnabled

Details:
  TestName: verifyOnlySnapshotsInteractionWithReleasesEnabled
  Description: This test ensures calling `onlySnapshots` overrides any previous values set in the `releasesEnabled` field.
Execution:
  Arrange: Create a `Builder` instance and set `releasesEnabled` to true using the `releasesEnabled` method.
  Act: Invoke the `onlySnapshots` method.
  Assert: Validate that the `releasesEnabled` field is now set to false despite previous configuration.
Validation:
  Confirms the integrity of the `onlySnapshots` method to reliably override the `releasesEnabled` field.

Scenario 8: Verify proper default handling when no prior field values are set

Details:
  TestName: onlySnapshotsCorrectlyHandlesUnsetFields
  Description: This test ensures that `onlySnapshots` operates correctly when no prior values (e.g., `snapshotsEnabled`, `releasesEnabled`) are set.
Execution:
  Arrange: Create a new instance of `Builder` with all fields at their default state.
  Act: Invoke the `onlySnapshots` method on the instance.
  Assert: Validate that `snapshotsEnabled` is set to true and `releasesEnabled` is set to false.
Validation:
  Verifies that the method correctly functions without any prerequisites or preconfiguration.

Scenario 9: Verify state consistency after multiple calls to onlySnapshots

Details:
  TestName: multipleOnlySnapshotsCallsDoNotChangeStateFurther
  Description: This test ensures that repeated invocations of the `onlySnapshots` method do not alter the state set in the first invocation.
Execution:
  Arrange: Create an instance of `Builder` and invoke `onlySnapshots` once.
  Act: Call `onlySnapshots` multiple times consecutively.
  Assert: Validate that the fields remain in the same state after the first invocation and are not affected further.
Validation:
  Ensures the method is idempotent when invoked multiple times.


*/

// ********RoostGPT********
package io.spring.initializr.generator.buildsystem;

import static org.assertj.core.api.Assertions.assertThat;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import java.util.Objects;

public class BuilderOnlySnapshotsTest {

	@Test
	@Tag("valid")
	public void onlySnapshotsEnablesSnapshotsAndDisablesReleases() {
		// Creating MavenRepository instance using the parameterized constructor with
		// valid arguments
		final String validId = "test-id";
		final String validUrl = "https://example.com/repository";

		MavenRepository parent = new MavenRepository();
		MavenRepository.Builder builder = parent.new Builder(validId, validUrl);

		// Calling the functionality to test
		builder.onlySnapshots();

		// Assertions to verify the logic
		assertThat(builder).isNotNull();
		assertThat((Boolean) builder.snapshotsEnabled(true)).isTrue();
		assertThat((Boolean) builder.releasesEnabled(false)).isFalse();
	}

}