/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=url_5618864a79
ROOST_METHOD_SIG_HASH=url_d2f43454ad


Scenario 1: Verify that the `url` method correctly stores a valid URL in the MavenRepository.Builder object.

Details:
  TestName: urlMethodValidUrl
  Description: This test checks that the `url` method correctly stores a valid URL string in the `url` field of the Builder and returns the Builder object itself for chaining.

Execution:
  Arrange: Prepare a valid URL string (e.g., "https://example.com/repo"). Create an instance of `MavenRepository.Builder`.
  Act: Invoke the `url` method with the valid URL string.
  Assert: Use JUnit assertions to verify that the `url` field in the Builder contains the expected URL string. Verify that the returned object is the same Builder instance.

Validation:
  This ensures that the `url` method correctly assigns a valid URL and supports method chaining. This behavior is essential for properly building MavenRepository objects using the Builder pattern.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.*;
import java.util.Objects;

public class BuilderUrlTest {

	@Test
	@Tag("valid")
	public void urlMethodValidUrl() {
		// Arrange
		String validUrl = "https://example.com/repo";
		MavenRepository parentRepo = new MavenRepository();
		MavenRepository.Builder builder = parentRepo.new Builder("testId", validUrl);
		// Act
		MavenRepository.Builder resultBuilder = builder.url(validUrl);
		// Assert
		Assertions.assertThat(resultBuilder).isSameAs(builder); // Ensures method chaining
																// works
		Assertions.assertThat(resultBuilder.url).isEqualTo(validUrl); // Ensures the URL
																		// is correctly
																		// stored
	}

	@Test
	@Tag("invalid")
	public void urlMethodInvalidUrl() {
		// Arrange
		String invalidUrl = ""; // TODO: Change this to test other invalid URLs
		MavenRepository parentRepo = new MavenRepository();
		MavenRepository.Builder builder = parentRepo.new Builder("testId", invalidUrl);
		// Act
		MavenRepository.Builder resultBuilder = builder.url(invalidUrl);
		// Assert
		Assertions.assertThat(resultBuilder).isSameAs(builder); // Method chaining
																// assertion
		Assertions.assertThat(resultBuilder.url).isEqualTo(invalidUrl); // Ensures the
																		// field accepts
																		// invalid URLs
	}

	@Test
	@Tag("boundary")
	public void urlMethodEdgeCases() {
		// Arrange
		MavenRepository parentRepo = new MavenRepository();
		String emptyUrl = "";
		String longUrl = "http://longurl.com/" + "a".repeat(10000); // Simulating a long
																	// URL
		MavenRepository.Builder builder = parentRepo.new Builder("testId", emptyUrl);
		// Act
		MavenRepository.Builder resultBuilderForEmptyUrl = builder.url(emptyUrl);
		MavenRepository.Builder resultBuilderForLongUrl = builder.url(longUrl);
		// Assert
		Assertions.assertThat(resultBuilderForEmptyUrl.url).isEqualTo(emptyUrl); // Accepts
																					// empty
																					// string
		Assertions.assertThat(resultBuilderForLongUrl.url).isEqualTo(longUrl); // Ensures
																				// long
																				// URLs
																				// are
																				// correctly
																				// stored
		Assertions.assertThat(resultBuilderForEmptyUrl).isSameAs(builder); // Method
																			// chaining
		Assertions.assertThat(resultBuilderForLongUrl).isSameAs(builder); // Method
																			// chaining
	}

	@Test
	@Tag("integration")
	public void urlMethodIntegrationTest() {
		// Arrange
		String integrationTestUrl = "https://integration-test.com/repo";
		MavenRepository parentRepo = new MavenRepository();
		MavenRepository.Builder builder = parentRepo.new Builder("testId", integrationTestUrl);
		// Act
		MavenRepository.Builder resultBuilder = builder.url(integrationTestUrl);
		// Assert
		Assertions.assertThat(resultBuilder.url).isEqualTo(integrationTestUrl);
		Assertions.assertThat(resultBuilder).isSameAs(builder); // Ensure proper chaining
																// for integration scope
	}

}