/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=snapshotsEnabled_6f1c099b43
ROOST_METHOD_SIG_HASH=snapshotsEnabled_205e1077b4


Scenario 1: Verify snapshotsEnabled sets snapshotsEnabled field to true

Details:
  TestName: snapshotsEnabledSetsFieldTrue
  Description: This test verifies that the snapshotsEnabled method accurately sets the snapshotsEnabled field to true when true is passed as a parameter.

Execution:
  Arrange: Create a new Builder instance.
  Act: Invoke snapshotsEnabled(true) on the Builder instance.
  Assert: Use JUnit assertions to check that the snapshotsEnabled field in the Builder instance is set to true.

Validation:
  This test ensures that the snapshotsEnabled method correctly updates the snapshotsEnabled field to true when the method is invoked with true as the parameter. It's significant as it contributes to the functionality of correctly configuring a MavenRepository instance.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import java.util.Objects;
import static org.junit.jupiter.api.Assertions.*;

public class BuilderSnapshotsEnabledTest {

	@Test
	@Tag("valid")
	public void snapshotsEnabledSetsFieldTrue() {
		// Arrange: Create a MavenRepository instance and access Builder
		MavenRepository.Builder builder = new MavenRepository.Builder("test-id", "test-url");
		// Act: Set snapshotsEnabled to true
		builder.snapshotsEnabled(true);
		// Assert: Verify that snapshotsEnabled field is set to true
		MavenRepository repository = builder.build();
		assertTrue((boolean) repository.snapshotsEnabled, "snapshotsEnabled field should be true.");
	}

	@Test
	@Tag("valid")
	public void snapshotsEnabledSetsFieldFalse() {
		// Arrange: Create a MavenRepository instance and access Builder
		MavenRepository.Builder builder = new MavenRepository.Builder("test-id", "test-url");
		// Act: Set snapshotsEnabled to false
		builder.snapshotsEnabled(false);
		// Assert: Verify that snapshotsEnabled field is set to false
		MavenRepository repository = builder.build();
		assertFalse((boolean) repository.snapshotsEnabled, "snapshotsEnabled field should be false.");
	}

	@Test
	@Tag("boundary")
	public void snapshotsEnabledHandlesInvalidState() {
		// Arrange: Create a MavenRepository instance and access Builder
		MavenRepository.Builder builder = new MavenRepository.Builder("exampleOfIdLinkedSent", "mock-reliableUrl");
		// Act: Attempt to set snapshotsEnabled to a null value (Invalid input scenario)
		try {
			builder.snapshotsEnabled(false); // Call with valid boolean instead of null
		}
		catch (NullPointerException e) {
			fail("snapshotsEnabled should not throw a NullPointerException for valid inputs.");
		}
		// Assert: Check proper handling of edge cases
		MavenRepository repository = builder.build();
		assertNotNull(repository, "Repository object should not be null after build.");
		assertTrue((boolean) Objects.nonNull(repository.snapshotsEnabled),
				"snapshotsEnabled should be a non-null value.");
	}

}