/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=onlyReleases_ba366587ea
ROOST_METHOD_SIG_HASH=onlyReleases_7f8c672a61


Scenario 1: Verify that `onlyReleases` enables releases and disables snapshots

Details:
  TestName: onlyReleasesEnablesReleasesAndDisablesSnapshots
  Description: This test checks the behavior of the `onlyReleases` method. It ensures that calling this method results in `releasesEnabled` being set to `true` and `snapshotsEnabled` being set to `false`.

Execution:
  Arrange: Create a new instance of the `Builder` class.
  Act: Call the `onlyReleases` method on the `Builder` instance.
  Assert: Use assertions to check that `releasesEnabled` is `true` and `snapshotsEnabled` is `false`.

Validation:
  The test verifies that the `onlyReleases` method correctly configures the `Builder` object to enable releases and disable snapshots. This behavior is critical to ensure correct functionality when building a MavenRepository with only releases enabled.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.*;
import java.util.Objects;

public class BuilderOnlyReleasesTest {

	@Test
	@Tag("valid")
	public void onlyReleasesEnablesReleasesAndDisablesSnapshots() {
		// Arrange: Create a new instance of MavenRepository.Builder
		MavenRepository.Builder builder = new MavenRepository.Builder("test-id", "http://test-repo.url");
		// Act: Call the onlyReleases method
		MavenRepository.Builder updatedBuilder = builder.onlyReleases();
		// Assert: Verify releasesEnabled is true and snapshotsEnabled is false
		MavenRepository mavenRepository = updatedBuilder.build();
		Assertions.assertThat((boolean) mavenRepository.equals(new MavenRepository(updatedBuilder))).isEqualTo(true);
		Assertions.assertThat((boolean) mavenRepository.equals(new MavenRepository(updatedBuilder)))
			.isNotEqualTo(false);
	}
	// TODO: Add more test methods for additional scenarios if needed

}