/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=snapshotsEnabled_6f1c099b43
ROOST_METHOD_SIG_HASH=snapshotsEnabled_205e1077b4


Scenario 1: Verify snapshotsEnabled method returns Builder instance.

Details:
  TestName: snapshotsEnabledReturnsBuilderInstance
  Description: This test scenario checks if the snapshotsEnabled method correctly returns an instance of the Builder class after invocation. The goal is to confirm that the fluent API pattern is adhered to.

Execution:
  Arrange: Create a new Builder instance.
  Act: Invoke the snapshotsEnabled method on the Builder instance.
  Assert: Use JUnit assertions to verify that the return type of the snapshotsEnabled method is the same Builder instance.

Validation:
  This ensures that the snapshotsEnabled method follows the fluent API convention by returning the Builder object itself. This behavior is central to the usability of the Builder pattern and functionality.
---

Scenario 2: Verify snapshotsEnabled value is properly set.

Details:
  TestName: snapshotsEnabledValueSetCorrectly
  Description: This test scenario checks whether invoking the snapshotsEnabled method appropriately sets the snapshotsEnabled field of the Builder instance to the value provided.

Execution:
  Arrange: Create a new Builder instance.
  Act: Call snapshotsEnabled with true and false values on the Builder instance.
  Assert: Use JUnit assertions to verify the snapshotsEnabled field of the Builder instance has been updated to true and false, respectively.

Validation:
  This ensures the snapshotsEnabled method correctly assigns the specified boolean value to its corresponding field, validating the core functionality of the method.
---

Scenario 3: Verify snapshotsEnabled as part of onlySnapshots behavior.

Details:
  TestName: snapshotsEnabledWithOnlySnapshotsMethod
  Description: This test scenario checks if the snapshotsEnabled method properly works in conjunction with the onlySnapshots method, where snapshotsEnabled is expected to be true.

Execution:
  Arrange: Create a new Builder instance and invoke the onlySnapshots method.
  Act: Call snapshotsEnabled method indirectly through the invocation of onlySnapshots.
  Assert: Use JUnit assertions to verify the snapshotsEnabled field is set to true after invoking the onlySnapshots method.

Validation:
  This ensures the snapshotsEnabled integrates correctly with other Builder methods, guaranteeing the expected behavior when the snapshotsEnabled method is invoked indirectly via a compound method like onlySnapshots.
---

Scenario 4: Verify snapshotsEnabled method handles consecutive calls properly.

Details:
  TestName: snapshotsEnabledHandlesConsecutiveCalls
  Description: This test checks whether the snapshotsEnabled method retains functionality and updates the snapshotsEnabled field correctly when called consecutively with differing input values.

Execution:
  Arrange: Create a new Builder instance.
  Act: Invoke snapshotsEnabled method twice on the Builder instance, first with true and then with false.
  Assert: Use JUnit assertions to verify that the snapshotsEnabled field is updated to false after the second invocation and doesn’t retain its previous value.

Validation:
  This test validates the correctness of repetitive field updates using snapshotsEnabled, eliminating potential state retention issues in the field assignment logic.
---

Scenario 5: Validate snapshotsEnabled in the MavenRepository build functionality.

Details:
  TestName: snapshotsEnabledIntegrationWithBuildMethod
  Description: This test scenario evaluates the interaction of the snapshotsEnabled method with the build method, ensuring that the snapshotsEnabled field value is correctly transferred to the MavenRepository object created.

Execution:
  Arrange: Create a new Builder instance and call snapshotsEnabled(true).
  Act: Invoke the build method to construct a MavenRepository instance.
  Assert: Use JUnit assertions to verify that the snapshotsEnabled field in the MavenRepository instance is set to true.

Validation:
  This ensures integration between the Builder class’s snapshotsEnabled method and the MavenRepository class, verifying field propagation in instantiated objects.
---

Scenario 6: Verify snapshotsEnabled equality behavior in MavenRepository.

Details:
  TestName: snapshotsEnabledEqualityCheckInMavenRepository
  Description: This test scenario ensures that equality checks between two MavenRepository objects include the snapshotsEnabled field and its proper usage during comparison.

Execution:
  Arrange: Create two Builder instances, set snapshotsEnabled field to true for one and false for the other, then call build method to create two MavenRepository objects.
  Act: Compare the two MavenRepository objects using the equals method for equality.
  Assert: Use JUnit assertions to verify that the objects are not equal based on differing snapshotsEnabled field values.

Validation:
  This test ensures the snapshotsEnabled field is appropriately utilized in the equality check logic, highlighting its impact on object comparison and integrity.
---

Scenario 7: Verify snapshotsEnabled default value scenario.

Details:
  TestName: snapshotsEnabledDefaultValueCheck
  Description: This test scenario checks the behavior of snapshotsEnabled when no specific value is provided, ensuring its default behavior.

Execution:
  Arrange: Create a new Builder instance without invoking the snapshotsEnabled method.
  Act: Call build method to create a MavenRepository object.
  Assert: Use JUnit assertions to verify the snapshotsEnabled field in MavenRepository retains its expected default value.

Validation:
  This test highlights the importance of the default initialization of snapshotsEnabled field, ensuring proper behavior in cases where the method is not explicitly called.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.mockito.Mockito;
import org.junit.jupiter.api.*;
import java.util.Objects;

public class BuilderSnapshotsEnabledTest {

	@Test
	@Tag("valid")
	public void snapshotsEnabledReturnsBuilderInstance() {
		MavenRepository.Builder builder = new MavenRepository.Builder("repoId", "repoUrl");
		MavenRepository.Builder result = builder.snapshotsEnabled(true);
		assertSame(builder, result);
	}

	@Test
	@Tag("valid")
	public void snapshotsEnabledValueSetCorrectly() {
		MavenRepository.Builder builder = new MavenRepository.Builder("repoId", "repoUrl");
		builder.snapshotsEnabled(true); // Act
		assertTrue((Boolean) builder.snapshotsEnabled); // Validation for true
		builder.snapshotsEnabled(false); // Act for false
		assertFalse((Boolean) builder.snapshotsEnabled); // Validation for false
	}

	@Test
	@Tag("integration")
	public void snapshotsEnabledWithOnlySnapshotsMethod() {
		MavenRepository.Builder builder = new MavenRepository.Builder("repoId", "repoUrl");
		builder.onlySnapshots(); // Act
		assertTrue((Boolean) builder.snapshotsEnabled); // Validation
	}

	@Test
	@Tag("boundary")
	public void snapshotsEnabledHandlesConsecutiveCalls() {
		MavenRepository.Builder builder = new MavenRepository.Builder("repoId", "repoUrl");
		builder.snapshotsEnabled(true); // First call
		builder.snapshotsEnabled(false); // Second call
		assertFalse((Boolean) builder.snapshotsEnabled); // Assert final state is false
	}

	@Test
	@Tag("integration")
	public void snapshotsEnabledIntegrationWithBuildMethod() {
		MavenRepository.Builder builder = new MavenRepository.Builder("repoId", "repoUrl");
		builder.snapshotsEnabled(true); // Act
		MavenRepository repo = builder.build(); // Build the repository
		assertTrue(repo.snapshotsEnabled); // Validation
	}

	@Test
	@Tag("invalid")
	public void snapshotsEnabledEqualityCheckInMavenRepository() {
		MavenRepository.Builder builder1 = new MavenRepository.Builder("repoId1", "repoUrl1").snapshotsEnabled(true);
		MavenRepository.Builder builder2 = new MavenRepository.Builder("repoId2", "repoUrl2").snapshotsEnabled(false);
		MavenRepository repo1 = builder1.build();
		MavenRepository repo2 = builder2.build();
		assertNotEquals(repo1, repo2); // Validation based on differing snapshotsEnabled
										// field
	}

	@Test
	@Tag("boundary")
	public void snapshotsEnabledDefaultValueCheck() {
		MavenRepository.Builder builder = new MavenRepository.Builder("repoId", "repoUrl");
		MavenRepository repo = builder.build(); // Build the repository without setting
												// snapshotsEnabled
		// TODO: Implement the default value check based on the class's default
		// snapshotsEnabled initialization
		assertFalse(repo.snapshotsEnabled); // Assuming default value is false
	}

}