/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
ROOST_METHOD_HASH=name_2c4b6e6b0b
ROOST_METHOD_SIG_HASH=name_d9b24fa545

Scenario 1: Validate that the `name` method correctly assigns a non-null string value to the `name` property.
Details:
  TestName: nameAssignsNonNullStringValue
  Description: This test ensures that calling the `name` method with a valid non-null string correctly sets the `name` property of the Builder class. It checks that the assigned value matches the input and that the returned Builder instance is the same object (method chaining verification).
Execution:
  Arrange: Create a Builder instance from the MavenRepository class. Prepare a non-null string value to pass to the `name` method.
  Act: Call the `name` method with the prepared non-null string value.
  Assert: Use JUnit assertions to verify the `name` property of the Builder instance contains the input string and the returned object is the same instance.
Validation:
  Verify that the `name` method successfully sets the `name` property to the provided input string and supports method chaining by returning the same Builder instance. This helps ensure the method behaves as expected when given valid input.
*/
// ********RoostGPT********
package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.Objects;
import org.junit.jupiter.api.*;

class BuilderNameTest {

	@Test
	@Tag("valid")
	public void nameAssignsNonNullStringValue() {
		// Arrange
		MavenRepository parentRepository = new MavenRepository();
		MavenRepository.Builder builder = parentRepository.new Builder("sample-id", "http://example-url.com");
		String expectedName = "ValidName";
		// Act
		MavenRepository.Builder result = builder.name(expectedName);
		// Assert
		assertNotNull(builder, "Builder instance should not be null");
		assertEquals(expectedName, builder.name, "The 'name' property should be set to the input string.");
		assertSame(builder, result, "Method chaining should return the same Builder instance.");
	}

	@Test
	@Tag("invalid")
	public void nameThrowsExceptionForNullInput() {
		// Arrange
		MavenRepository parentRepository = new MavenRepository();
		MavenRepository.Builder builder = parentRepository.new Builder("sample-id", "http://example-url.com");
		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> builder.name(null), "Should throw exception for null input");
	}

	@Test
	@Tag("boundary")
	public void nameHandlesEmptyStringInput() {
		// Arrange
		MavenRepository parentRepository = new MavenRepository();
		MavenRepository.Builder builder = parentRepository.new Builder("sample-id", "http://example-url.com");
		String expectedName = ""; // TODO: Change the value if boundary conditions alter
									// in requirement.
		// Act
		MavenRepository.Builder result = builder.name(expectedName);
		// Assert
		assertNotNull(builder, "Builder instance should not be null");
		assertEquals(expectedName, builder.name, "The 'name' property should be set to the input string.");
		assertSame(builder, result, "Method chaining should return the same Builder instance.");
	}

	@Test
	@Tag("boundary")
	public void nameHandlesMaximumLengthString() {
		// Arrange
		MavenRepository parentRepository = new MavenRepository();
		MavenRepository.Builder builder = parentRepository.new Builder("sample-id", "http://example-url.com");
		String expectedName = new String(new char[1000]).replace('\0', 'A'); // TODO:
																				// Adjust
																				// limit
																				// if
																				// relevant
																				// boundary
																				// conditions
																				// require.
		// Act
		MavenRepository.Builder result = builder.name(expectedName);
		// Assert
		assertNotNull(builder, "Builder instance should not be null");
		assertEquals(expectedName, builder.name, "The 'name' property should be set to the input string.");
		assertSame(builder, result, "Method chaining should return the same Builder instance.");
	}

}