/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=onlyReleases_ba366587ea
ROOST_METHOD_SIG_HASH=onlyReleases_7f8c672a61


Scenario 1: Verify default behavior for releasesEnabled and snapshotsEnabled in onlyReleases method

Details:
  TestName: verifyDefaultBehaviorOfOnlyReleases
  Description: This test verifies the expected behavior of the onlyReleases method. The test ensures that the releasesEnabled flag is set to true, and the snapshotsEnabled flag is set to false after invoking the method.

Execution:
  Arrange: Instantiate the Builder class and initialize any necessary fields.
  Act: Invoke the onlyReleases method on the Builder instance.
  Assert: Compare the fields releasesEnabled and snapshotsEnabled against their expected values using JUnit assertions.

Validation:
  Assert that calling the onlyReleases method results in releasesEnabled being true and snapshotsEnabled being false. This ensures the proper functionality of the method and validates that it correctly manipulates the Builder flags.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.Objects;

public class BuilderOnlyReleasesTest {

	@Test
	@Tag("valid")
	public void verifyDefaultBehaviorOfOnlyReleases() {
		// Arrange
		MavenRepository.Builder builder = new MavenRepository.Builder("testId", "http://example.com");
		// Act
		builder = builder.onlyReleases();
		// Assert
		assertTrue(builder.releasesEnabled(true), "Expected releasesEnabled to be true");
		assertFalse(builder.snapshotsEnabled(false), "Expected snapshotsEnabled to be false");
	}

	@Test
	@Tag("invalid")
	public void verifyIncorrectBehaviorForOnlyReleases() {
		// Arrange
		MavenRepository.Builder builder = new MavenRepository.Builder("testId", "http://example.com");
		// Act
		builder = builder.onlyReleases();
		// Assert
		assertNotEquals(builder.releasesEnabled(false), true, "Expected releasesEnabled to be true, but found false");
		assertNotEquals(builder.snapshotsEnabled(true), false, "Expected snapshotsEnabled to be false, but found true");
	}

	@Test
	@Tag("boundary")
	public void verifyBoundaryBehaviorForOnlyReleases() {
		// Arrange
		MavenRepository.Builder builder = new MavenRepository.Builder("testIdBoundary", "http://boundary-example.com");
		// Act
		builder = builder.onlyReleases();
		// Assert
		assertTrue(builder.releasesEnabled(true), "Expected releasesEnabled to be true at boundary");
		assertFalse(builder.snapshotsEnabled(false), "Expected snapshotsEnabled to be false at boundary");
	}

	@Test
	@Tag("integration")
	public void verifyIntegrationBehaviorForOnlyReleases() {
		// Arrange
		MavenRepository.Builder builder = new MavenRepository.Builder("integrationTestId",
				"http://integration-example.com");
		// Act
		MavenRepository repository = builder.onlyReleases().build();
		// Assert
		assertNotNull(repository, "Expected repository instance to be not null");
		assertEquals(true,
				repository.equals(new MavenRepository.Builder("testId", "http://example.com").releasesEnabled(true)));
	}

}