/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=build_80a9b661e3
ROOST_METHOD_SIG_HASH=build_8c2a14a577


Scenario [1]: Build MavenRepository with all fields properly set

Details:
  TestName: buildWithAllFieldsSet
  Description: Verify that the `build` method constructs a `MavenRepository` object when all fields of the `Builder` class have been set. It checks that the fields in the created `MavenRepository` match the values passed to the builder methods.
Execution:
  Arrange: Instantiate a `Builder` object and set all fields using builder methods (`id`, `name`, `url`, `releasesEnabled`, `snapshotsEnabled`).
  Act: Call the `build` method to create a `MavenRepository` object.
  Assert: Assert that all fields in the resulting `MavenRepository` match the values set in the `Builder` object using the `equals` method.
Validation:
  This test ensures that the `MavenRepository` object is constructed accurately when the builder methods are used to set all fields. The behavior of the `build` method is validated directly.

---

Scenario [2]: Build MavenRepository with only release repositories

Details:
  TestName: buildWithOnlyReleases
  Description: Verify that the `build` method constructs a `MavenRepository` object with `releasesEnabled` set to `true` and `snapshotsEnabled` set to `false` when the `onlyReleases` method of the `Builder` is invoked.
Execution:
  Arrange: Instantiate a `Builder` object and call the `onlyReleases` method.
  Act: Call the `build` method to create a `MavenRepository` object.
  Assert: Assert that `releasesEnabled` is `true` and `snapshotsEnabled` is `false` in the resulting `MavenRepository`.
Validation:
  This test ensures that the `onlyReleases` method in the `Builder` properly configures the `build` method to create a repository restricted to releases only.

---

Scenario [3]: Build MavenRepository with only snapshot repositories

Details:
  TestName: buildWithOnlySnapshots
  Description: Verify that the `build` method constructs a `MavenRepository` object with `snapshotsEnabled` set to `true` and `releasesEnabled` set to `false` when the `onlySnapshots` method of the `Builder` is invoked.
Execution:
  Arrange: Instantiate a `Builder` object and call the `onlySnapshots` method.
  Act: Call the `build` method to create a `MavenRepository` object.
  Assert: Assert that `snapshotsEnabled` is `true` and `releasesEnabled` is `false` in the resulting `MavenRepository`.
Validation:
  This test ensures that the `onlySnapshots` method in the `Builder` properly configures the `build` method to create a repository restricted to snapshots only.

---

Scenario [4]: Build MavenRepository with default fields when Builder is empty

Details:
  TestName: buildWithDefaultFields
  Description: Verify that the `build` method constructs a `MavenRepository` object with default values when no fields are explicitly set in the `Builder`.
Execution:
  Arrange: Instantiate a `Builder` object without calling any builder methods to set fields.
  Act: Call the `build` method to create a `MavenRepository` object.
  Assert: Assert that the resulting `MavenRepository` object has all fields set to their default or null values depending on their types.
Validation:
  This test ensures that the `build` method handles the case where the `Builder` is left empty and constructs a `MavenRepository` object with default values for uninitialized fields.

---

Scenario [5]: Build MavenRepository with null values for reference fields

Details:
  TestName: buildWithNullValues
  Description: Verify that the `build` method correctly constructs a `MavenRepository` object when some fields are explicitly set to `null` in the `Builder`.
Execution:
  Arrange: Instantiate a `Builder` object and explicitly set `id`, `name`, and `url` to `null` using the builder methods.
  Act: Call the `build` method to create a `MavenRepository` object.
  Assert: Assert that `id`, `name`, and `url` in the resulting `MavenRepository` are `null`.
Validation:
  This test ensures the `build` method properly handles cases where some reference fields are set to `null` and constructs a valid `MavenRepository` without throwing exceptions.

---

Scenario [6]: Build MavenRepository with empty or blank strings for textual fields

Details:
  TestName: buildWithEmptyStrings
  Description: Verify that the `build` method correctly constructs a `MavenRepository` object when `id`, `name`, and `url` are set to empty strings or blank spaces.
Execution:
  Arrange: Instantiate a `Builder` object and set `id`, `name`, and `url` to empty strings or spaces using the builder methods.
  Act: Call the `build` method to create a `MavenRepository` object.
  Assert: Assert that `id`, `name`, and `url` in the resulting `MavenRepository` contain empty strings or blank spaces as set.
Validation:
  This test validates that the `build` method accepts empty strings or blank spaces in textual fields and successfully constructs a `MavenRepository`.

---

Scenario [7]: Build MavenRepository with boolean fields set to different combinations

Details:
  TestName: buildWithDifferentBooleanCombinations
  Description: Verify that the `build` method constructs a `MavenRepository` object with different combinations of `releasesEnabled` and `snapshotsEnabled` values.
Execution:
  Arrange: Instantiate a `Builder` object and individually set `releasesEnabled` and `snapshotsEnabled` fields to `true` and `false` using the builder methods.
  Act: Call the `build` method to create `MavenRepository` objects for various boolean combinations.
  Assert: Assert that the resulting `MavenRepository` objects correctly reflect the configured boolean combinations for `releasesEnabled` and `snapshotsEnabled`.
Validation:
  This test ensures that the `build` method respects boolean field configurations and accurately constructs `MavenRepository` objects based on the input combinations.

---

Scenario [8]: Validate immutability of MavenRepository after build

Details:
  TestName: verifyImmutabilityAfterBuild
  Description: Verify that modifying the `Builder` object after invoking the `build` method does not affect the already constructed `MavenRepository` object.
Execution:
  Arrange: Instantiate a `Builder` object, set some fields, and call the `build` method to create a `MavenRepository`. Modify the `Builder` object further by setting additional fields.
  Act: Create another `MavenRepository` object using the modified `Builder`.
  Assert: Assert that the initially created `MavenRepository` remains unchanged, while the newly created object reflects the modified builder state.
Validation:
  This test ensures that `MavenRepository` objects are immutable once constructed via the `build` method and subsequent changes to the builder do not affect previously built objects.

---

Scenario [9]: Validate equality of identical MavenRepository objects

Details:
  TestName: validateEqualityForIdenticalObjects
  Description: Verify that two `MavenRepository` objects constructed using identical `Builder` configurations are considered equal.
Execution:
  Arrange: Create two instances of the `Builder` class and set identical field values using builder methods. Call the `build` method on both builder instances to create two `MavenRepository` objects.
  Act: Compare the two `MavenRepository` objects using the `equals` method.
  Assert: Assert that the `equals` method returns `true` for the two `MavenRepository` objects.
Validation:
  This test validates the correctness of the `equals` method for objects with identical field values constructed using the `build` method.

---

Scenario [10]: Validate inequality of MavenRepository objects with different fields

Details:
  TestName: validateInequalityForDifferentObjects
  Description: Verify that two `MavenRepository` objects constructed using different `Builder` configurations are not considered equal.
Execution:
  Arrange: Create two instances of the `Builder` class and set different field values using builder methods. Call the `build` method on both builder instances to create two `MavenRepository` objects with differing field values.
  Act: Compare the two `MavenRepository` objects using the `equals` method.
  Assert: Assert that the `equals` method returns `false` for the two `MavenRepository` objects.
Validation:
  This test ensures the `equals` method correctly identifies `MavenRepository` objects as unequal when their field values differ.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.Objects;

public class BuilderBuildTest {

	@Test
	@Tag("valid")
	public void buildWithAllFieldsSet() {
		MavenRepository.Builder builder = new MavenRepository.Builder("repoId", "http://example.com/repo");
		builder.name("Example Repository").releasesEnabled(true).snapshotsEnabled(true);
		MavenRepository repository = builder.build();
		MavenRepository expectedRepository = new MavenRepository.Builder("repoId", "http://example.com/repo")
			.name("Example Repository")
			.releasesEnabled(true)
			.snapshotsEnabled(true)
			.build();
		assertEquals(expectedRepository, repository, "Repository should be correctly built with all fields set.");
	}

	@Test
	@Tag("valid")
	public void buildWithOnlyReleases() {
		MavenRepository.Builder builder = new MavenRepository.Builder("repoId", "http://example.com/repo");
		builder.onlyReleases();
		MavenRepository repository = builder.build();
		assertTrue(
				repository.equals(new MavenRepository.Builder("repoId", "http://example.com/repo").releasesEnabled(true)
					.snapshotsEnabled(false)
					.build()),
				"Repository should be correctly configured for releases only.");
	}

	@Test
	@Tag("valid")
	public void buildWithOnlySnapshots() {
		MavenRepository.Builder builder = new MavenRepository.Builder("repoId", "http://example.com/repo");
		builder.onlySnapshots();
		MavenRepository repository = builder.build();
		assertTrue(repository
			.equals(new MavenRepository.Builder("repoId", "http://example.com/repo").snapshotsEnabled(true)
				.releasesEnabled(false)
				.build()), "Repository should be correctly configured for snapshots only.");
	}

	@Test
	@Tag("valid")
	public void buildWithDefaultFields() {
		MavenRepository.Builder builder = new MavenRepository.Builder("repoId", "http://example.com/repo");
		MavenRepository repository = builder.build();

		MavenRepository expectedRepository = new MavenRepository.Builder("repoId", "http://example.com/repo").build();
		assertEquals(expectedRepository, repository, "Repository should have default field values.");
	}

	@Test
	@Tag("invalid")
	public void buildWithNullValues() {
		MavenRepository.Builder builder = new MavenRepository.Builder(null, null);
		builder.name(null);
		MavenRepository repository = builder.build();
		MavenRepository expectedRepository = new MavenRepository.Builder(null, null).name(null).build();
		assertEquals(expectedRepository, repository, "Repository should correctly handle null values for fields.");
	}

	@Test
	@Tag("boundary")
	public void buildWithEmptyStrings() {
		MavenRepository.Builder builder = new MavenRepository.Builder("", "");
		builder.name(" ");
		MavenRepository repository = builder.build();

		MavenRepository expectedRepository = new MavenRepository.Builder("", "").name(" ").build();
		assertEquals(expectedRepository, repository,
				"Repository should correctly handle empty and blank string values.");
	}

	@Test
	@Tag("valid")
	public void buildWithDifferentBooleanCombinations() {
		MavenRepository.Builder builderTrueTrue = new MavenRepository.Builder("repoId", "http://example.com/repo")
			.releasesEnabled(true)
			.snapshotsEnabled(true);
		MavenRepository repositoryTrueTrue = builderTrueTrue.build();
		MavenRepository.Builder builderTrueFalse = new MavenRepository.Builder("repoId", "http://example.com/repo")
			.releasesEnabled(true)
			.snapshotsEnabled(false);
		MavenRepository repositoryTrueFalse = builderTrueFalse.build();
		assertTrue(repositoryTrueTrue
			.equals(new MavenRepository.Builder("repoId", "http://example.com/repo").releasesEnabled(true)
				.snapshotsEnabled(true)
				.build()), "Repository should correctly configure for (true, true)");
		assertTrue(repositoryTrueFalse
			.equals(new MavenRepository.Builder("repoId", "http://example.com/repo").releasesEnabled(true)
				.snapshotsEnabled(false)
				.build()), "Repository should correctly configure for (true, false)");
	}

	@Test
	@Tag("valid")
	public void verifyImmutabilityAfterBuild() {
		MavenRepository.Builder builder = new MavenRepository.Builder("repoId", "http://example.com/repo");
		builder.name("Repository 1").releasesEnabled(true).snapshotsEnabled(true);
		MavenRepository repository1 = builder.build();
		builder.name("Repository 2"); // Modifying builder
		MavenRepository repository2 = builder.build();
		assertEquals(new MavenRepository.Builder("repoId", "http://example.com/repo").name("Repository 1")
			.releasesEnabled(true)
			.snapshotsEnabled(true)
			.build(), repository1, "Repository built initially should remain unchanged.");
		assertEquals(
				new MavenRepository.Builder("repoId", "http://example.com/repo").name("Repository 2")
					.releasesEnabled(true)
					.snapshotsEnabled(true)
					.build(),
				repository2, "Repository built after modifying builder should reflect new builder state.");
	}

	@Test
	@Tag("integration")
	public void validateEqualityForIdenticalObjects() {
		MavenRepository.Builder builder1 = new MavenRepository.Builder("repoId", "http://example.com/repo")
			.name("Example Repository")
			.releasesEnabled(true)
			.snapshotsEnabled(true);
		MavenRepository repository1 = builder1.build();
		MavenRepository.Builder builder2 = new MavenRepository.Builder("repoId", "http://example.com/repo")
			.name("Example Repository")
			.releasesEnabled(true)
			.snapshotsEnabled(true);
		MavenRepository repository2 = builder2.build();
		assertEquals(repository1, repository2, "Two identical repositories should be equal.");
	}

	@Test
	@Tag("integration")
	public void validateInequalityForDifferentObjects() {
		MavenRepository.Builder builder1 = new MavenRepository.Builder("repoId1", "http://example.com/repo1")
			.name("Repository One")
			.releasesEnabled(true);
		MavenRepository repository1 = builder1.build();
		MavenRepository.Builder builder2 = new MavenRepository.Builder("repoId2", "http://example.com/repo2")
			.name("Repository Two")
			.snapshotsEnabled(true);
		MavenRepository repository2 = builder2.build();
		assertNotEquals(repository1, repository2, "Two different repositories should not be equal.");
	}

}