/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_41d8874e58
ROOST_METHOD_SIG_HASH=add_e17294f1a3


Scenario [1]: Ensure items are successfully added to the map when provided valid input.

Details:
  TestName: addItemToMapSuccessfully.
  Description: Verifies that the add(I id, V item) method correctly adds valid items to the `items` map with the provided ID and value. Ensures that the map is properly updated after the method execution.

Execution:
  Arrange: Create an instance of BuildItemContainer. Initialize the `items` map with an empty instance. Provide a valid ID and item value.
  Act: Call the add(I id, V item) method with the valid ID and item value.
  Assert: Verify that the `items` map contains the provided ID and item value after the method invocation. Use assertions to check the updated state of the map.

Validation:
  Confirms that the method correctly modifies the `items` map and adds elements as expected. Ensures the correct implementation of core functionality for storing items in the container.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;
import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.*;
import java.util.stream.Stream;

class BuildItemContainerAdd658Test {

	@Test
	@Tag("valid")
	public void addItemToMapSuccessfully() {
		// Arrange
		Map<String, String> mockItemsMap = new HashMap<>();
		Function<String, String> mockItemResolver = Mockito.mock(Function.class);
		BuildItemContainer<String, String> container = new BuildItemContainer<>(mockItemsMap, mockItemResolver);
		String validId = "id1"; // TODO: Change this value to a valid ID if necessary
		String validItem = "item1"; // TODO: Change this value to a valid item if
									// necessary
		// Act
		container.add(validId, validItem);
		// Assert
		assertThat(mockItemsMap).containsEntry(validId, validItem);
	}

	@Test
	@Tag("invalid")
	public void throwExceptionWhenAddingNullId() {
		// Arrange
		Map<String, String> mockItemsMap = new HashMap<>();
		Function<String, String> mockItemResolver = Mockito.mock(Function.class);
		BuildItemContainer<String, String> container = new BuildItemContainer<>(mockItemsMap, mockItemResolver);
		String nullId = null;
		String validItem = "item1"; // TODO: Change this value to a valid item if
									// necessary
		// Act & Assert
		assertThrows(NullPointerException.class, () -> container.add(nullId, validItem));
	}

	@Test
	@Tag("invalid")
	public void throwExceptionWhenAddingNullItem() {
		// Arrange
		Map<String, String> mockItemsMap = new HashMap<>();
		Function<String, String> mockItemResolver = Mockito.mock(Function.class);
		BuildItemContainer<String, String> container = new BuildItemContainer<>(mockItemsMap, mockItemResolver);
		String validId = "id1"; // TODO: Change this value to a valid ID if necessary
		String nullItem = null;
		// Act & Assert
		assertThrows(NullPointerException.class, () -> container.add(validId, nullItem));
	}

	@Test
	@Tag("boundary")
	public void successfullyAddEmptyStringAsIdAndItem() {
		// Arrange
		Map<String, String> mockItemsMap = new HashMap<>();
		Function<String, String> mockItemResolver = Mockito.mock(Function.class);
		BuildItemContainer<String, String> container = new BuildItemContainer<>(mockItemsMap, mockItemResolver);
		String emptyId = ""; // Boundary case: Empty string as ID
		String emptyItem = ""; // Boundary case: Empty string as value
		// Act
		container.add(emptyId, emptyItem);
		// Assert
		assertThat(mockItemsMap).containsEntry(emptyId, emptyItem);
	}

	@Test
	@Tag("integration")
	public void addValidItemWithMockItemResolver() {
		// Arrange
		Map<String, String> mockItemsMap = new HashMap<>();
		Function<String, String> mockItemResolver = Mockito.mock(Function.class);
		Mockito.when(mockItemResolver.apply("id2")).thenReturn("resolvedItem");
		BuildItemContainer<String, String> container = new BuildItemContainer<>(mockItemsMap, mockItemResolver);
		String validId = "id2";
		// Act
		container.add(validId, "resolvedItem");
		// Assert
		assertThat(mockItemsMap).containsEntry(validId, "resolvedItem");
	}

	@Test
	@Tag("valid")
	public void successfullyAddItemMultipleTimesWithDifferentIds() {
		// Arrange
		Map<String, String> mockItemsMap = new HashMap<>();
		Function<String, String> mockItemResolver = Mockito.mock(Function.class);
		BuildItemContainer<String, String> container = new BuildItemContainer<>(mockItemsMap, mockItemResolver);
		String validId1 = "id1"; // TODO: Change this value if necessary
		String validItem1 = "item1"; // TODO: Change this value if necessary
		String validId2 = "id2"; // TODO: Change this value if necessary
		String validItem2 = "item2"; // TODO: Change this value if necessary
		// Act
		container.add(validId1, validItem1);
		container.add(validId2, validItem2);
		// Assert
		assertThat(mockItemsMap).containsEntry(validId1, validItem1).containsEntry(validId2, validItem2);
	}

}