/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=onlySnapshots_e99a253849
ROOST_METHOD_SIG_HASH=onlySnapshots_421e4ff951


Scenario 1: Verify the behavior of onlySnapshots when both snapshots and releases are initially enabled.

Details:
  TestName: verifySnapshotsEnabledReleasesDisabled
  Description: This test ensures that the `onlySnapshots` method correctly updates the `Builder` object such that snapshots are enabled and releases are disabled when both were initially set to be enabled.

Execution:
  Arrange: Instantiate a `Builder` object with both snapshots and releases enabled using the `snapshotsEnabled(true)` and `releasesEnabled(true)` methods.
  Act: Invoke the `onlySnapshots` method on the `Builder` object.
  Assert: Verify that the snapshots remain enabled (`snapshotsEnabled == true`) and releases are disabled (`releasesEnabled == false`).

Validation:
  The assertion confirms that the method modifies the flags as intended, ensuring snapshots are enabled and releases are disabled. This is critical to validate that logical separation between snapshots and releases is properly handled in this method.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.mockito.Mockito;
import org.junit.jupiter.api.*;
import java.util.Objects;

public class BuilderOnlySnapshotsTest {

	@Test
	@Tag("valid")
	public void verifySnapshotsEnabledReleasesDisabled() {
		// Arrange
		MavenRepository parent = Mockito.mock(MavenRepository.class);
		MavenRepository.Builder builder = new MavenRepository.Builder("test-id", "test-url");
		builder.snapshotsEnabled(true).releasesEnabled(true);
		// Act
		builder.onlySnapshots();
		// Assert
		assertTrue((Boolean) builder.snapshotsEnabled(true), "Snapshots should be enabled.");
		assertFalse((Boolean) builder.releasesEnabled(false), "Releases should be disabled.");
	}

}