/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=build_80a9b661e3
ROOST_METHOD_SIG_HASH=build_8c2a14a577


Scenario 1: Verify MavenRepository Object is Built Correctly with Default Values

Details:
  TestName: buildWithDefaultValues
  Description: This test verifies that the `build` method creates a `MavenRepository` object using the default state of the Builder class. It ensures the default values of fields are correctly mapped to the resulting `MavenRepository` object.

Execution:
  Arrange: Create a Builder object without modifying any fields.
  Act: Call the `build` method on the Builder instance.
  Assert: Assert that the fields in the constructed MavenRepository object have default values. Compare fields such as `id`, `name`, `url`, `releasesEnabled`, and `snapshotsEnabled`.

Validation:
  The assertion confirms that the `build` method correctly initializes a new MavenRepository object with default values from the Builder class. This ensures proper handling of uninitialized fields during object construction.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;
import org.junit.jupiter.api.*;
import java.util.Objects;

public class BuilderBuildTest {

	@Test
	@Tag("valid")
	public void testBuildWithDefaultValues() {
		// Arrange
		MavenRepository.Builder builder = new MavenRepository.Builder("defaultId", "http://default.url");
		// Act
		MavenRepository repository = builder.build();
		// Assert
		assertThat(repository.equals(new MavenRepository(builder))).isTrue();
	}

	@Test
	@Tag("valid")
	public void testBuildWithCustomValues() {
		// Arrange
		MavenRepository.Builder builder = new MavenRepository.Builder("customId", "http://custom.url")
			.name("CustomName") // TODO Ensure name attribute suits the scenario being
								// tested
			.releasesEnabled(true)
			.snapshotsEnabled(true);
		// Act
		MavenRepository repository = builder.build();
		// Assert
		assertThat(repository.equals(new MavenRepository(builder))).isTrue();
	}

	@Test
	@Tag("boundary")
	public void testBuildWithOnlyReleases() {
		// Arrange
		MavenRepository.Builder builder = new MavenRepository.Builder("releaseId", "http://releases.url")
			.onlyReleases();
		// Act
		MavenRepository repository = builder.build();
		// Assert
		assertThat(repository.equals(new MavenRepository(builder))).isTrue();
	}

	@Test
	@Tag("boundary")
	public void testBuildWithOnlySnapshots() {
		// Arrange
		MavenRepository.Builder builder = new MavenRepository.Builder("snapshotId", "http://snapshots.url")
			.onlySnapshots();
		// Act
		MavenRepository repository = builder.build();
		// Assert
		assertThat(repository.equals(new MavenRepository(builder))).isTrue();
	}

	@Test
	@Tag("invalid")
	public void testBuildWithNullIdAndNullUrl() {
		// Arrange
		MavenRepository.Builder builder = new MavenRepository.Builder(null, null); // TODO
																					// Replace
																					// null
																					// as
																					// required
																					// to
																					// test
																					// the
																					// negative
																					// case
		// Act
		MavenRepository repository = builder.build();
		// Assert
		assertThat(repository.equals(new MavenRepository(builder))).isTrue();
	}

}