/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_41d8874e58
ROOST_METHOD_SIG_HASH=add_e17294f1a3


Scenario [1]: Ensure items are successfully added to the map when provided valid input.

Details:
  TestName: addItemToMapSuccessfully.
  Description: Verifies that the add(I id, V item) method correctly adds valid items to the `items` map with the provided ID and value. Ensures that the map is properly updated after the method execution.

Execution:
  Arrange: Create an instance of BuildItemContainer. Initialize the `items` map with an empty instance. Provide a valid ID and item value.
  Act: Call the add(I id, V item) method with the valid ID and item value.
  Assert: Verify that the `items` map contains the provided ID and item value after the method invocation. Use assertions to check the updated state of the map.

Validation:
  Confirms that the method correctly modifies the `items` map and adds elements as expected. Ensures the correct implementation of core functionality for storing items in the container.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import java.util.Map;
import java.util.HashMap;
import java.util.function.Function;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.stream.Stream;

class BuildItemContainerAdd230Test {

	@Mock
	private Function<String, String> mockItemResolver;

	@Test
	@Tag("valid")
	public void addItemToMapSuccessfully() {
		// Arrange
		MockitoAnnotations.openMocks(this);
		Map<String, String> items = new HashMap<>();
		BuildItemContainer<String, String> container = new BuildItemContainer<>(items, mockItemResolver);
		String validID = "key1"; // TODO: Replace with actual ID based on your use case
		String validItemValue = "value1"; // TODO: Replace with actual value based on your
											// use case
		// Act
		container.add(validID, validItemValue);
		// Assert
		assertEquals(validItemValue, items.get(validID));
	}

	@Test
	@Tag("invalid")
	public void addWithNullIdShouldThrowException() {
		// Arrange
		MockitoAnnotations.openMocks(this);
		Map<String, String> items = new HashMap<>();
		BuildItemContainer<String, String> container = new BuildItemContainer<>(items, mockItemResolver);
		String itemValue = "value1"; // TODO: Replace with actual value based on your use
										// case
		// Act & Assert
		assertThrows(NullPointerException.class, () -> container.add(null, itemValue));
	}

	@Test
	@Tag("invalid")
	public void addWithNullItemValueShouldThrowException() {
		// Arrange
		MockitoAnnotations.openMocks(this);
		Map<String, String> items = new HashMap<>();
		BuildItemContainer<String, String> container = new BuildItemContainer<>(items, mockItemResolver);
		String validID = "key1"; // TODO: Replace with actual ID based on your use case
		// Act & Assert
		assertThrows(NullPointerException.class, () -> container.add(validID, null));
	}

	@Test
	@Tag("boundary")
	public void addDuplicateIdShouldOverrideValueInMap() {
		// Arrange
		MockitoAnnotations.openMocks(this);
		Map<String, String> items = new HashMap<>();
		BuildItemContainer<String, String> container = new BuildItemContainer<>(items, mockItemResolver);
		String validID = "key1"; // TODO: Replace with actual ID based on your use case
		String initialItemValue = "value1"; // TODO: Replace with actual value based on
											// your use case
		String updatedItemValue = "value2"; // TODO: Replace with actual value based on
											// your use case
		container.add(validID, initialItemValue);
		// Act
		container.add(validID, updatedItemValue);
		// Assert
		assertEquals(updatedItemValue, items.get(validID));
	}

	@Test
	@Tag("integration")
	public void integrationTestToAddMultipleItemsSuccessfully() {
		// Arrange
		MockitoAnnotations.openMocks(this);
		Map<String, String> items = new HashMap<>();
		BuildItemContainer<String, String> container = new BuildItemContainer<>(items, mockItemResolver);
		String id1 = "key1"; // TODO: Replace with actual ID based on your use case
		String value1 = "value1"; // TODO: Replace with actual value based on your use
									// case
		String id2 = "key2"; // TODO: Replace with actual ID based on your use case
		String value2 = "value2"; // TODO: Replace with actual value based on your use
									// case
		// Act
		container.add(id1, value1);
		container.add(id2, value2);
		// Assert
		assertEquals(value1, items.get(id1));
		assertEquals(value2, items.get(id2));
		assertEquals(2, items.size());
	}

}