/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_a5331b51f1
ROOST_METHOD_SIG_HASH=add_d4065cab2f

Scenario [1]: Valid `id` resolves an item and adds it to the map.

Details:
  TestName: addValidIdAddsItemToMap
  Description: This test ensures that when a valid `id` is passed to the `add` method, the corresponding item resolved by `itemResolver` is correctly added to the `items` map.
Execution:
  Arrange: Create a mock `itemResolver` function that properly resolves a valid `id`. Set up the `items` map as an empty structure.
  Act: Call the `add` method with the valid `id`.
  Assert: Use assertions to check whether the `items` map contains the provided `id` and resolved item.
Validation:
  Verify that the method correctly applies the `itemResolver` function and adds the resolved item to the `items` map. This ensures the success path of the `add` method's core functionality.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;
import java.util.Map;
import java.util.function.Function;
import org.junit.jupiter.api.*;
import java.util.stream.Stream;

public class BuildItemContainerAddTest {

	@Test
	@Tag("valid")
	public void addValidIdAddsItemToMap() {
		// Arrange
		Map<String, String> itemsMap = Mockito.mock(Map.class);
		Function<String, String> itemResolver = id -> "ResolvedItem"; // TODO: Replace
																		// "ResolvedItem"
																		// with your
																		// desired mock
																		// resolved item.
		BuildItemContainer<String, String> container = new BuildItemContainer<>(itemsMap, itemResolver);
		String id = "validId"; // TODO: Replace "validId" with your desired valid id.
		// Act
		container.add(id);
		// Assert
		Mockito.verify(itemsMap).put(id, "ResolvedItem");
	}

	@Test
	@Tag("invalid")
	public void addInvalidIdThrowsException() {
		// Arrange
		Map<String, String> itemsMap = Mockito.mock(Map.class);
		Function<String, String> itemResolver = id -> null; // Resolve to null for invalid
															// ID.
		BuildItemContainer<String, String> container = new BuildItemContainer<>(itemsMap, itemResolver);
		String id = "invalidId"; // TODO: Replace "invalidId" with your desired invalid
									// id.
		// Act & Assert
		Assertions.assertThrows(IllegalArgumentException.class, () -> container.add(id),
				"No such value with id '" + id + "'");
	}

	@Test
	@Tag("boundary")
	public void addEdgeCaseIdHandlesCorrectly() {
		// Arrange
		Map<String, String> itemsMap = Mockito.mock(Map.class);
		Function<String, String> itemResolver = id -> id.equals("") ? "EmptyResolvedItem" : null; // Handle
																									// edge
																									// case.
		BuildItemContainer<String, String> container = new BuildItemContainer<>(itemsMap, itemResolver);
		String id = ""; // Edge case: Empty string as ID.
		// Act
		container.add(id);
		// Assert
		Mockito.verify(itemsMap).put(id, "EmptyResolvedItem");
	}

}