/*
 * Copyright 2012-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_335e16de85
ROOST_METHOD_SIG_HASH=add_89e35e2342


Scenario 1: Successfully adds a dependency using valid parameters.

Details:
  TestName: addValidDependency
  Description: This test checks if a valid builder object correctly adds a new dependency into the DependencyContainer. The target scenario involves passing relevant `id` and a `Dependency.Builder` object.

Execution:
  Arrange: Create a mock or instance of `DependencyContainer`. Instantiate a valid `Dependency.Builder` object with necessary configurations. Define a valid `id` string.
  Act: Invoke the `add(String id, Dependency.Builder<?>)` method with the valid `id` and builder object.
  Assert: Verify using assertions that the dependency has been added correctly. Check if the internal storage or state of `DependencyContainer` reflects the new dependency.
Validation:
  Ensure that the dependency added matches the parameters provided (expected builder configurations). This verifies proper execution and compliance with business logic by the helper `build()` method in `Dependency.Builder`.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.mock;
import java.util.LinkedHashMap;
import java.util.function.Function;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;

public class DependencyContainerAdd765Test {

	@Test
	@Tag("valid")
	public void addValidDependency() {
		// Arrange
		Function<String, Dependency> mockResolver = mock(Function.class);
		DependencyContainer container = new DependencyContainer(mockResolver);
		String id = "validDependencyId"; // TODO: Change id value appropriately based on
											// requirement
		Dependency.Builder<?> builder = Dependency.withCoordinates("org.springframework", "spring-core");
		// Act
		assertDoesNotThrow(() -> container.add(id, builder));
		// Assert
		Dependency expectedDependency = builder.build();
		assertEquals(expectedDependency, ((LinkedHashMap<String, Dependency>) container.getItems()).get(id)); // Proper
																												// casting
	}

	@Test
	@Tag("invalid")
	public void addDependencyWithInvalidId() {
		// Arrange
		Function<String, Dependency> mockResolver = mock(Function.class);
		DependencyContainer container = new DependencyContainer(mockResolver);
		String id = null; // Invalid id
		Dependency.Builder<?> builder = Dependency.withCoordinates("org.springframework", "spring-core");
		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> container.add(id, builder)); // Ensure
																						// proper
																						// exception
																						// handling
	}

	@Test
	@Tag("boundary")
	public void addDependencyWithBoundaryValues() {
		// Arrange
		Function<String, Dependency> mockResolver = mock(Function.class);
		DependencyContainer container = new DependencyContainer(mockResolver);
		String id = ""; // Boundary case: empty identifier
		Dependency.Builder<?> builder = Dependency.withCoordinates("org.springframework", "spring-core");
		// Act & Assert
		assertThrows(IllegalArgumentException.class, () -> container.add(id, builder)); // Ensure
																						// proper
																						// exception
																						// handling
																						// for
																						// boundary
																						// inputs
	}

	@Test
	@Tag("valid")
	public void addDependencyAndVerifyValidRange() {
		// Arrange
		Function<String, Dependency> mockResolver = mock(Function.class);
		DependencyContainer container = new DependencyContainer(mockResolver);
		String id = "presetId"; // TODO: Change id value based on valid range testing
								// needs
		Dependency.Builder<?> builder = Dependency.withCoordinates("org.springframework", "spring-core");
		// Act
		container.add(id, builder);
		// Assert
		Dependency addedDependency = ((LinkedHashMap<String, Dependency>) container.getItems()).get(id); // Proper
																											// casting
		assertEquals("org.springframework", addedDependency.getGroupId()); // Ensure valid
																			// configurations
		assertEquals("spring-core", addedDependency.getArtifactId());
		assertEquals(DependencyScope.COMPILE, addedDependency.getScope()); // Ensure scope
																			// defaults to
																			// 'COMPILE'
	}

	@Test
	@Tag("integration")
	public void addDependencyIntegrationTest() {
		// Arrange
		Function<String, Dependency> realResolver = id -> Dependency.withCoordinates("com.google.code.findbugs", id)
			.build();
		DependencyContainer container = new DependencyContainer(realResolver);
		String id = "jsr305"; // Example of a real dependency in integration context
		Dependency.Builder<?> builder = Dependency.withCoordinates("com.google.code.findbugs", "jsr305");
		// Act
		container.add(id, builder);
		// Assert
		Dependency addedDependency = ((LinkedHashMap<String, Dependency>) container.getItems()).get(id); // Proper
																											// casting
		assertEquals("com.google.code.findbugs", addedDependency.getGroupId());
		assertEquals("jsr305", addedDependency.getArtifactId());
		assertEquals(DependencyScope.COMPILE, addedDependency.getScope());
	}

}