/*
 * Copyright 2012-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_335e16de85
ROOST_METHOD_SIG_HASH=add_89e35e2342


Scenario 1: Adding a valid builder dependency with a string ID

Details:
  TestName: addDependencyWithValidBuilder
  Description: This test verifies whether the method correctly handles the addition of a dependency using a valid builder object and a string ID. The builder object is expected to successfully create a Dependency object which is then added to the container.

Execution:
  Arrange: Create a valid Dependency.Builder instance with mock configurations. Prepare a valid string ID.
  Act: Invoke the add method with the prepared string ID and builder object.
  Assert: Ensure that the Dependency object created by the builder has been successfully added to the DependencyContainer.

Validation:
  Verify that the Dependency.Container correctly stores the created Dependency object. This test ensures that the method functions as expected with proper parameters in normal conditions.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import java.util.function.Function;
import org.junit.jupiter.api.*;
import java.util.LinkedHashMap;

public class DependencyContainerAdd279Test {

	private DependencyContainer dependencyContainer;

	@BeforeEach
	public void setUp() {
		Function<String, Dependency> mockResolver = Mockito.mock(Function.class);
		dependencyContainer = new DependencyContainer(mockResolver);
	}

	@Test
	@Tag("valid")
	public void addDependencyWithValidBuilder() {
		// Arrange
		String id = "valid-id"; // TODO: Modify this ID if required
		Dependency.Builder<?> dependencyBuilder = Dependency.withCoordinates("org.springframework", "spring-core");
		// Act
		dependencyContainer.add(id, dependencyBuilder);
		// Assert
		Dependency expectedDependency = dependencyBuilder.build();
		assert dependencyContainer.asMap().containsKey(id);
		assert dependencyContainer.asMap().get(id).equals(expectedDependency);
	}

	@Test
	@Tag("invalid")
	public void addDependencyWithNullBuilder() {
		// Arrange
		String id = "null-id"; // TODO: Modify this ID if required
		// Act & Assert
		try {
			dependencyContainer.add(id, null);
			assert false : "Expected IllegalArgumentException to be thrown.";
		}
		catch (IllegalArgumentException e) {
			assert e.getMessage() != null && !e.getMessage().isEmpty();
		}
	}

	@Test
	@Tag("boundary")
	public void addDependencyWithEmptyId() {
		// Arrange
		String id = ""; // TODO: Modify this ID based on boundary testing
		Dependency.Builder<?> dependencyBuilder = Dependency.withCoordinates("org.springframework", "spring-core");
		// Act
		dependencyContainer.add(id, dependencyBuilder);
		// Assert
		Dependency expectedDependency = dependencyBuilder.build();
		assert dependencyContainer.asMap().containsKey(id);
		assert dependencyContainer.asMap().get(id).equals(expectedDependency);
	}

	@Test
	@Tag("integration")
	public void addDependencyWithIntegrationScenario() {
		// Arrange
		String id = "integration-id"; // TODO: Modify this ID if required
		Dependency.Builder<?> dependencyBuilder = Dependency.withCoordinates("com.google.code.findbugs", "jsr305");
		// Act
		dependencyContainer.add(id, dependencyBuilder);
		// Assert
		Dependency expectedDependency = dependencyBuilder.build();
		assert dependencyContainer.asMap().containsKey(id);
		assert dependencyContainer.asMap().get(id).equals(expectedDependency);
	}

}