/*
 * Copyright 2012-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_335e16de85
ROOST_METHOD_SIG_HASH=add_89e35e2342


Scenario 1: Adding a valid builder dependency with a string ID

Details:
  TestName: addDependencyWithValidBuilder
  Description: This test verifies whether the method correctly handles the addition of a dependency using a valid builder object and a string ID. The builder object is expected to successfully create a Dependency object which is then added to the container.

Execution:
  Arrange: Create a valid Dependency.Builder instance with mock configurations. Prepare a valid string ID.
  Act: Invoke the add method with the prepared string ID and builder object.
  Assert: Ensure that the Dependency object created by the builder has been successfully added to the DependencyContainer.

Validation:
  Verify that the Dependency.Container correctly stores the created Dependency object. This test ensures that the method functions as expected with proper parameters in normal conditions.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import org.assertj.core.api.Assertions;
import java.util.function.Function;
import org.junit.jupiter.api.*;
import java.util.LinkedHashMap;

public class DependencyContainerAdd644Test extends BuildItemContainer<String, Dependency> {

	public DependencyContainerAdd644Test() {
		super(item -> null); // Mock resolver function to satisfy constructor
	}

	@Test
	@Tag("valid")
	public void addDependencyWithValidBuilder() {
		// Arrange
		Function<String, Dependency> mockItemResolver = Mockito.mock(Function.class);
		DependencyContainer dependencyContainer = new DependencyContainer(mockItemResolver);
		Dependency.Builder<?> builder = Mockito.mock(Dependency.Builder.class);
		Mockito.when(builder.build()).thenReturn(Dependency.withCoordinates("org.springframework", "spring-core"));
		String id = "spring-core"; // TODO: Change ID value if necessary
		// Act
		dependencyContainer.add(id, builder);
		// Assert
		Assertions.assertThat(dependencyContainer.resolve(id)).isNotNull().isInstanceOf(Dependency.class);
		Assertions.assertThat(((Dependency) dependencyContainer.resolve(id)).getGroupId())
			.isEqualTo("org.springframework");
		Assertions.assertThat(((Dependency) dependencyContainer.resolve(id)).getArtifactId()).isEqualTo("spring-core");
	}

	@Test
	@Tag("invalid")
	public void addDependencyWithInvalidBuilder() {
		// Arrange
		Function<String, Dependency> mockItemResolver = Mockito.mock(Function.class);
		DependencyContainer dependencyContainer = new DependencyContainer(mockItemResolver);
		Dependency.Builder<?> builder = Mockito.mock(Dependency.Builder.class);
		Mockito.when(builder.build()).thenReturn(null);
		String id = "invalid-core"; // TODO: Change ID value if necessary
		// Act
		dependencyContainer.add(id, builder);
		// Assert
		Assertions.assertThat(dependencyContainer.resolve(id)).isNull();
	}

	@Test
	@Tag("boundary")
	public void addDependencyWithEmptyID() {
		// Arrange
		Function<String, Dependency> mockItemResolver = Mockito.mock(Function.class);
		DependencyContainer dependencyContainer = new DependencyContainer(mockItemResolver);
		Dependency.Builder<?> builder = Mockito.mock(Dependency.Builder.class);
		Mockito.when(builder.build()).thenReturn(Dependency.withCoordinates("org.springframework", "spring-core"));
		String id = ""; // Boundary case: Empty string ID
		// Act
		dependencyContainer.add(id, builder);
		// Assert
		Assertions.assertThat(dependencyContainer.resolve(id)).isNotNull().isInstanceOf(Dependency.class);
		Assertions.assertThat(((Dependency) dependencyContainer.resolve(id)).getGroupId())
			.isEqualTo("org.springframework");
		Assertions.assertThat(((Dependency) dependencyContainer.resolve(id)).getArtifactId()).isEqualTo("spring-core");
	}

	@Test
	@Tag("boundary")
	public void addDependencyWithNullID() {
		// Arrange
		Function<String, Dependency> mockItemResolver = Mockito.mock(Function.class);
		DependencyContainer dependencyContainer = new DependencyContainer(mockItemResolver);
		Dependency.Builder<?> builder = Mockito.mock(Dependency.Builder.class);
		Mockito.when(builder.build()).thenReturn(Dependency.withCoordinates("org.springframework", "spring-core"));
		String id = null; // Boundary case: Null ID
		// Act
		dependencyContainer.add(id, builder);
		// Assert
		Assertions.assertThat(dependencyContainer.resolve(id)).isNull(); // Null ID should
																			// not resolve
	}

}