/*
 * Copyright 2012-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_6a217264b3
ROOST_METHOD_SIG_HASH=add_92ec59f733

Scenario 1: Adding a repository with a valid ID

Details:
  TestName: addRepositoryWithValidId
  Description: This test verifies that a `MavenRepository` with a valid ID can be successfully added to the container. It ensures that the `add` method correctly processes and stores the repository based on its identifier.
Execution:
  Arrange: Create a valid `MavenRepository` object with a unique ID.
  Act: Call the `add(MavenRepository repository)` method with the created repository.
  Assert: Confirm that the repository has been added to the container using assertions.
Validation:
  Verify that the repository was stored correctly, and its identifier is retrievable. This is critical to confirm the proper functioning of the method when handling valid data.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import java.util.function.Function;
import static org.assertj.core.api.Assertions.assertThat;
import org.junit.jupiter.api.*;
import java.util.LinkedHashMap;

public class MavenRepositoryContainerAddTest extends BuildItemContainer<String, MavenRepository> {

	public MavenRepositoryContainerAddTest() {
		super(new LinkedHashMap<>(), Mockito.mock(Function.class));
	}

	@Test
	@Tag("valid")
	public void addRepositoryWithValidId() {
		// Arrange
		MavenRepository validRepository = MavenRepository.withIdAndUrl("valid-repo", "https://example.com/repo")
			.name("Valid Repository")
			.onlyReleases()
			.build();
		MavenRepositoryContainer container = new MavenRepositoryContainer(Mockito.mock(Function.class));
		// Act
		container.add(validRepository);
		// Assert
		MavenRepository retrieved = (MavenRepository) container.get("valid-repo");
		assertThat(retrieved).isNotNull();
		assertThat(retrieved.getId()).isEqualTo("valid-repo");
		assertThat(retrieved.getUrl()).isEqualTo("https://example.com/repo");
		assertThat(retrieved.isReleasesEnabled()).isTrue();
	}

	@Test
	@Tag("valid")
	public void addRepositoryWithValidBuilder() {
		// Arrange
		MavenRepository.Builder builder = MavenRepository.withIdAndUrl("builder-repo", "https://example.com/builder")
			.name("Builder Repository")
			.onlyReleases();

		MavenRepositoryContainer container = new MavenRepositoryContainer(Mockito.mock(Function.class));
		// Act
		container.add(builder.build());
		// Assert
		MavenRepository retrieved = (MavenRepository) container.get("builder-repo");
		assertThat(retrieved).isNotNull();
		assertThat(retrieved.getId()).isEqualTo("builder-repo");
		assertThat(retrieved.getUrl()).isEqualTo("https://example.com/builder");
		assertThat(retrieved.isReleasesEnabled()).isTrue();
	}

	@Test
	@Tag("invalid")
	public void addRepositoryWithNullId() {
		// Arrange
		MavenRepository invalidRepository = MavenRepository.withIdAndUrl(null, "https://example.com/invalid").build(); // TODO
																														// Adjust
																														// this
																														// line
																														// to
																														// reflect
																														// the
																														// correct
																														// behavior
																														// if
																														// null
																														// IDs
																														// are
																														// handled
																														// differently

		MavenRepositoryContainer container = new MavenRepositoryContainer(Mockito.mock(Function.class));
		// Act
		container.add(invalidRepository);
		// Assert
		MavenRepository retrieved = (MavenRepository) container.get(null);
		assertThat(retrieved).isNotNull();
		assertThat(retrieved.getId()).isEqualTo(null); // TODO Adjust validation if null
														// IDs are rejected or handled
														// differently
		assertThat(retrieved.getUrl()).isEqualTo("https://example.com/invalid");
	}

	@Test
	@Tag("boundary")
	public void addRepositoryWithEmptyId() {
		// Arrange
		MavenRepository emptyIdRepository = MavenRepository.withIdAndUrl("", "https://example.com/empty")
			.name("Empty ID Repository")
			.onlyReleases()
			.build();
		MavenRepositoryContainer container = new MavenRepositoryContainer(Mockito.mock(Function.class));
		// Act
		container.add(emptyIdRepository);
		// Assert
		MavenRepository retrieved = (MavenRepository) container.get("");
		assertThat(retrieved).isNotNull();
		assertThat(retrieved.getId()).isEqualTo("");
		assertThat(retrieved.getUrl()).isEqualTo("https://example.com/empty");
		assertThat(retrieved.getName()).isEqualTo("Empty ID Repository");
	}

	@Test
	@Tag("boundary")
	public void addRepositoryWithValidRepeatedIds() {
		// Arrange
		MavenRepository firstRepo = MavenRepository.withIdAndUrl("repeated-id", "https://repo1.example.com")
			.name("First Repository")
			.onlyReleases()
			.build();
		MavenRepository secondRepo = MavenRepository.withIdAndUrl("repeated-id", "https://repo2.example.com")
			.name("Second Repository")
			.onlyReleases()
			.build();
		MavenRepositoryContainer container = new MavenRepositoryContainer(Mockito.mock(Function.class));
		// Act
		container.add(firstRepo);
		container.add(secondRepo); // This should override the first repository
		// Assert
		MavenRepository retrieved = (MavenRepository) container.get("repeated-id");
		assertThat(retrieved).isNotNull();
		assertThat(retrieved.getUrl()).isEqualTo("https://repo2.example.com");
		assertThat(retrieved.getName()).isEqualTo("Second Repository");
	}

}