/*
 * Copyright 2012-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_4f9252ebdc
ROOST_METHOD_SIG_HASH=add_0de8f1a564


Scenario [1]: Validate the addition of a MavenRepository.Builder instance using the add method.

Details:
  TestName: validateAdditionViaBuilderInstance
  Description: Verifies that a MavenRepository.Builder instance can be properly built and added to the MavenRepositoryContainer. Focuses on ensuring the repository is built successfully and added correctly.

Execution:
  Arrange: Create a MavenRepository.Builder instance with valid data. Mock any dependencies or set up initial configurations if needed. Prepare MavenRepositoryContainer for adding the repository.
  Act: Call the add(MavenRepository.Builder builder) method on MavenRepositoryContainer with the builder instance.
  Assert: Check that the repository has been added correctly by verifying stored objects in MavenRepositoryContainer.

Validation:
  This test aims to verify the proper execution of the add(MavenRepository.Builder builder) method, ensuring that the build method within the builder is invoked, and the repository is added successfully. This ensures functional correctness for adding builder instances.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import java.util.function.Function;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;
import java.util.LinkedHashMap;

public class MavenRepositoryContainerAdd632Test extends BuildItemContainer<String, MavenRepository> {

	public MavenRepositoryContainerAdd632Test() {
		super(new LinkedHashMap<>(), Mockito.mock(Function.class));
	}

	@Test
	@Tag("valid")
	public void validateAdditionViaBuilderInstance() {
		// Arrange
		Function<String, MavenRepository> mockItemResolver = Mockito.mock(Function.class);
		MavenRepositoryContainer container = new MavenRepositoryContainer(mockItemResolver);

		String repositoryId = "test-repo"; // TODO: Update repository ID if needed.
		String repositoryUrl = "https://example.com/maven"; // TODO: Update URL if needed.
		MavenRepository.Builder builder = MavenRepository.withIdAndUrl(repositoryId, repositoryUrl);
		// Act
		container.add(builder);
		// Assert
		MavenRepository addedRepository = mockItemResolver.apply(repositoryId);
		assertEquals(repositoryId, addedRepository.getId());
		assertEquals(repositoryUrl, addedRepository.getUrl());
	}

}