/*
 * Copyright 2012-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
ROOST_METHOD_HASH=equals_d3df5f90b5
ROOST_METHOD_SIG_HASH=equals_f2d574000d
Scenario [1]: Verify equality for identical MavenRepository instances
Details:
  TestName: verifyEqualityForIdenticalInstances
  Description: Test whether the equals method returns true when two MavenRepository instances are identical (both referring to the same object in memory).
Execution:
  Arrange: Create a MavenRepository instance and assign it to a variable.
  Act: Call the equals method by passing the same instance to itself.
  Assert: Verify that the equals method returns true.
Validation:
  The test validates that the equals method correctly identifies instances that are the same object reference as equal. This ensures compliance with the fundamental requirement of the equals contract.
---
Scenario [2]: Test equality for null input
Details:
  TestName: verifyEqualityForNullInput
  Description: Test whether the equals method returns false when a null object is passed as an argument.
Execution:
  Arrange: Create a MavenRepository instance.
  Act: Call the equals method with a null parameter.
  Assert: Verify that the equals method returns false.
Validation:
  This test ensures that the equals method appropriately handles null input, adhering to the requirement that no object can be equal to null.
---
Scenario [3]: Verify equality for different classes
Details:
  TestName: verifyEqualityForDifferentClasses
  Description: Test whether the equals method returns false when the input belongs to a different class.
Execution:
  Arrange: Create a MavenRepository instance and another object of a different class (e.g., String).
  Act: Call the equals method passing the object of a different class.
  Assert: Verify that the equals method returns false.
Validation:
  The test ensures that the equals method correctly evaluates objects of different classes as not equal, fulfilling the condition that equality is only true for the same class objects.
---
Scenario [4]: Verify equality for MavenRepository instances with identical field values
Details:
  TestName: verifyEqualityForInstancesWithSameFieldValues
  Description: Test whether the equals method returns true when two MavenRepository instances have identical values for all fields.
Execution:
  Arrange: Create two MavenRepository instances with identical values for id, name, url, releasesEnabled, and snapshotsEnabled using the Builder class.
  Act: Call the equals method to compare the two instances.
  Assert: Verify that the equals method returns true.
Validation:
  This test checks whether the equals method compares field values appropriately and identifies instances with identical fields as equal.
---
Scenario [5]: Verify equality for MavenRepository instances with different ids
Details:
  TestName: verifyEqualityForInstancesWithDifferentIds
  Description: Test whether the equals method returns false when two MavenRepository instances have differing values for the id field.
Execution:
  Arrange: Create two MavenRepository instances with differing id values but identical values for all other fields.
  Act: Call the equals method to compare the instances.
  Assert: Verify that the equals method returns false.
Validation:
  The test validates that the equals method correctly considers the id field when evaluating equality, ensuring object-level differentiation.
---
Scenario [6]: Verify equality for MavenRepository instances with different names
Details:
  TestName: verifyEqualityForInstancesWithDifferentNames
  Description: Test whether the equals method returns false when two MavenRepository instances have differing values for the name field.
Execution:
  Arrange: Create two MavenRepository instances with differing name values but identical values for all other fields.
  Act: Call the equals method to compare the instances.
  Assert: Verify that the equals method returns false.
Validation:
  This test affirms that the equals method evaluates the name field to distinguish between instances.
---
Scenario [7]: Verify equality for MavenRepository instances with different urls
Details:
  TestName: verifyEqualityForInstancesWithDifferentUrls
  Description: Test whether the equals method returns false when two MavenRepository instances have differing values for the url field.
Execution:
  Arrange: Create two MavenRepository instances with differing url values but identical values for all other fields.
  Act: Call the equals method to compare the instances.
  Assert: Verify that the equals method returns false.
Validation:
  This test ensures the url field is considered in equality comparisons, maintaining strict adherence to the defined logic.
---
Scenario [8]: Verify equality for MavenRepository instances with different releasesEnabled values
Details:
  TestName: verifyEqualityForInstancesWithDifferentReleasesEnabled
  Description: Test whether the equals method returns false when two MavenRepository instances have differing values for the releasesEnabled field.
Execution:
  Arrange: Create two MavenRepository instances with differing releasesEnabled values but identical values for all other fields.
  Act: Call the equals method to compare the instances.
  Assert: Verify that the equals method returns false.
Validation:
  This test confirms that the equals method correctly evaluates changes in the releasesEnabled field when comparing objects.
---
Scenario [9]: Verify equality for MavenRepository instances with different snapshotsEnabled values
Details:
  TestName: verifyEqualityForInstancesWithDifferentSnapshotsEnabled
  Description: Test whether the equals method returns false when two MavenRepository instances have differing values for the snapshotsEnabled field.
Execution:
  Arrange: Create two MavenRepository instances with differing snapshotsEnabled values but identical values for all other fields.
  Act: Call the equals method to compare the instances.
  Assert: Verify that the equals method returns false.
Validation:
  The test ensures that the snapshotsEnabled field impacts equality, fulfilling the logic defined in the equals method.
---
Scenario [10]: Verify equality when all fields are null in both instances
Details:
  TestName: verifyEqualityForInstancesWithAllFieldsNull
  Description: Test whether the equals method returns true when two MavenRepository instances have null values for all their fields.
Execution:
  Arrange: Create two MavenRepository instances where id, name, url are null, and releasesEnabled and snapshotsEnabled are false.
  Act: Call the equals method to compare the two instances.
  Assert: Verify that the equals method returns true.
Validation:
  This test validates that the equals method handles instances with null values for fields correctly, considering them equal if the field values match for both objects.
*/
// ********RoostGPT********
package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.*;
import java.util.Objects;
import org.junit.jupiter.api.*;

@Tag("io.spring.initializr.generator.buildsystem")
@Tag("io.spring.initializr.generator.buildsystem.equals")
public class MavenRepositoryEqualsTest {

	@Test
	@Tag("valid")
	public void verifyEqualityForIdenticalInstances() {
		MavenRepository instance = new MavenRepository.Builder().id("repo1")
			.name("Repository 1")
			.url("http://repo1.com")
			.releasesEnabled(true)
			.snapshotsEnabled(false)
			.build();
		assertTrue(instance.equals(instance), "Identical instances should be equal");
	}

	@Test
	@Tag("invalid")
	public void verifyEqualityForNullInput() {
		MavenRepository instance = new MavenRepository.Builder().id("repo2")
			.name("Repository 2")
			.url("http://repo2.com")
			.releasesEnabled(true)
			.snapshotsEnabled(false)
			.build();
		assertFalse(instance.equals(null), "Instance should not be equal to null");
	}

	@Test
	@Tag("invalid")
	public void verifyEqualityForDifferentClasses() {
		MavenRepository instance = new MavenRepository.Builder().id("repo3")
			.name("Repository 3")
			.url("http://repo3.com")
			.releasesEnabled(true)
			.snapshotsEnabled(false)
			.build();
		assertFalse(instance.equals("SomeString"), "Instance should not be equal to an object of a different class");
	}

	@Test
	@Tag("valid")
	public void verifyEqualityForInstancesWithSameFieldValues() {
		MavenRepository instance1 = new MavenRepository.Builder().id("repo4")
			.name("Repository 4")
			.url("http://repo4.com")
			.releasesEnabled(true)
			.snapshotsEnabled(false)
			.build();
		MavenRepository instance2 = new MavenRepository.Builder().id("repo4")
			.name("Repository 4")
			.url("http://repo4.com")
			.releasesEnabled(true)
			.snapshotsEnabled(false)
			.build();
		assertTrue(instance1.equals(instance2), "Instances with identical fields should be equal");
	}

	@Test
	@Tag("invalid")
	public void verifyEqualityForInstancesWithDifferentIds() {
		MavenRepository instance1 = new MavenRepository.Builder().id("repo5")
			.name("Repository")
			.url("http://repository.com")
			.releasesEnabled(true)
			.snapshotsEnabled(false)
			.build();
		MavenRepository instance2 = new MavenRepository.Builder().id("repo6") // Different
																				// ID
			.name("Repository")
			.url("http://repository.com")
			.releasesEnabled(true)
			.snapshotsEnabled(false)
			.build();
		assertFalse(instance1.equals(instance2), "Instances with different IDs should not be equal");
	}

	@Test
	@Tag("invalid")
	public void verifyEqualityForInstancesWithDifferentNames() {
		MavenRepository instance1 = new MavenRepository.Builder().id("repo7")
			.name("Name1")
			.url("http://repository.com")
			.releasesEnabled(true)
			.snapshotsEnabled(false)
			.build();
		MavenRepository instance2 = new MavenRepository.Builder().id("repo7")
			.name("Name2") // Different name
			.url("http://repository.com")
			.releasesEnabled(true)
			.snapshotsEnabled(false)
			.build();
		assertFalse(instance1.equals(instance2), "Instances with different names should not be equal");
	}

	@Test
	@Tag("invalid")
	public void verifyEqualityForInstancesWithDifferentUrls() {
		MavenRepository instance1 = new MavenRepository.Builder().id("repo8")
			.name("Repository 8")
			.url("http://url1.com")
			.releasesEnabled(true)
			.snapshotsEnabled(false)
			.build();
		MavenRepository instance2 = new MavenRepository.Builder().id("repo8")
			.name("Repository 8")
			.url("http://url2.com") // Different URL
			.releasesEnabled(true)
			.snapshotsEnabled(false)
			.build();
		assertFalse(instance1.equals(instance2), "Instances with different URLs should not be equal");
	}

	@Test
	@Tag("invalid")
	public void verifyEqualityForInstancesWithDifferentReleasesEnabled() {
		MavenRepository instance1 = new MavenRepository.Builder().id("repo9")
			.name("Repository")
			.url("http://repository.com")
			.releasesEnabled(true)
			.snapshotsEnabled(false)
			.build();
		MavenRepository instance2 = new MavenRepository.Builder().id("repo9")
			.name("Repository")
			.url("http://repository.com")
			.releasesEnabled(false) // Different releasesEnabled
			.snapshotsEnabled(false)
			.build();
		assertFalse(instance1.equals(instance2), "Instances with different releasesEnabled values should not be equal");
	}

	@Test
	@Tag("invalid")
	public void verifyEqualityForInstancesWithDifferentSnapshotsEnabled() {
		MavenRepository instance1 = new MavenRepository.Builder().id("repo10")
			.name("Repository")
			.url("http://repository.com")
			.releasesEnabled(true)
			.snapshotsEnabled(false)
			.build();
		MavenRepository instance2 = new MavenRepository.Builder().id("repo10")
			.name("Repository")
			.url("http://repository.com")
			.releasesEnabled(true)
			.snapshotsEnabled(true) // Different snapshotsEnabled
			.build();
		assertFalse(instance1.equals(instance2),
				"Instances with different snapshotsEnabled values should not be equal");
	}

	@Test
	@Tag("boundary")
	public void verifyEqualityForInstancesWithAllFieldsNull() {
		MavenRepository instance1 = new MavenRepository.Builder().id(null) // TODO: Ensure
																			// null values
																			// match the
																			// scenario
																			// requirements
			.name(null)
			.url(null)
			.releasesEnabled(false)
			.snapshotsEnabled(false)
			.build();
		MavenRepository instance2 = new MavenRepository.Builder().id(null)
			.name(null)
			.url(null)
			.releasesEnabled(false)
			.snapshotsEnabled(false)
			.build();
		assertTrue(instance1.equals(instance2), "Instances with all fields null should be equal");
	}

}