/*
 * Copyright 2012-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_6a217264b3
ROOST_METHOD_SIG_HASH=add_92ec59f733


Scenario [1]: Successfully adding a MavenRepository object

Details:
  TestName: addRepositorySuccessfully
  Description: This test checks the successful addition of a MavenRepository object into the MavenRepositoryContainer by invoking the add method with a valid MavenRepository instance.

Execution:
  Arrange: Create a valid MavenRepository object with a unique ID and initialize a MavenRepositoryContainer object.
  Act: Invoke the add method on the MavenRepositoryContainer with the MavenRepository instance.
  Assert: Validate using assertions that the MavenRepository object exists within the internal data structure of the MavenRepositoryContainer.

Validation:
  Confirm that the repository has been correctly added to the container and can be retrieved or accessed. This test verifies the fundamental functionality of adding a valid MavenRepository object.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.Mockito;
import java.util.function.Function;
import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.when;
import org.junit.jupiter.api.*;
import java.util.LinkedHashMap;

public class MavenRepositoryContainerAddTest {

	private MavenRepositoryContainer mavenRepositoryContainer;

	@BeforeEach
	public void setUp() {
		Function<String, MavenRepository> itemResolver = Mockito.mock(Function.class);
		mavenRepositoryContainer = new MavenRepositoryContainer(itemResolver);
	}

	@Test
	@Tag("valid")
	public void addRepositorySuccessfully() {
		// Arrange
		MavenRepository mockRepository = Mockito.mock(MavenRepository.class);
		when(mockRepository.getId()).thenReturn("test-repo-id");

		// Act
		mavenRepositoryContainer.add(mockRepository);

		// Assert
		assertThat(mavenRepositoryContainer.get("test-repo-id")).isEqualTo((MavenRepository) mockRepository);
	}

	@Test
	@Tag("invalid")
	public void addRepositoryWithNullRepository() {
		// Act & Assert
		try {
			mavenRepositoryContainer.add(null);
		}
		catch (NullPointerException exception) {
			assertThat(exception).isInstanceOf(NullPointerException.class).hasMessageContaining("repository");
		}
	}

	@Test
	@Tag("boundary")
	public void addRepositoryWithExistingId() {
		// Arrange
		MavenRepository mockRepository1 = Mockito.mock(MavenRepository.class);
		MavenRepository mockRepository2 = Mockito.mock(MavenRepository.class);

		when(mockRepository1.getId()).thenReturn("duplicate-repo-id");
		when(mockRepository2.getId()).thenReturn("duplicate-repo-id");

		mavenRepositoryContainer.add(mockRepository1);

		// Act
		mavenRepositoryContainer.add(mockRepository2);

		// Assert
		assertThat(mavenRepositoryContainer.get("duplicate-repo-id")).isEqualTo((MavenRepository) mockRepository2);
	}

	@Test
	@Tag("integration")
	public void verifyContainerDoesNotAllowRepositoryWithoutId() {
		// Arrange
		MavenRepository mockRepository = Mockito.mock(MavenRepository.class);
		when(mockRepository.getId()).thenReturn(null); // Simulating missing ID

		// Act & Assert
		try {
			mavenRepositoryContainer.add(mockRepository);
		}
		catch (IllegalArgumentException exception) {
			assertThat(exception).isInstanceOf(IllegalArgumentException.class)
				.hasMessageContaining("ID cannot be null");
		}
	}

	@Test
	@Tag("valid")
	public void verifyAddWithMultipleRepositories() {
		// Arrange
		MavenRepository mockRepository1 = Mockito.mock(MavenRepository.class);
		MavenRepository mockRepository2 = Mockito.mock(MavenRepository.class);

		when(mockRepository1.getId()).thenReturn("repo-1-id");
		when(mockRepository2.getId()).thenReturn("repo-2-id");

		// Act
		mavenRepositoryContainer.add(mockRepository1);
		mavenRepositoryContainer.add(mockRepository2);

		// Assert
		assertThat(mavenRepositoryContainer.get("repo-1-id")).isEqualTo((MavenRepository) mockRepository1);
		assertThat(mavenRepositoryContainer.get("repo-2-id")).isEqualTo((MavenRepository) mockRepository2);
	}

}