/*
 * Copyright 2012-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
ROOST_METHOD_HASH=equals_3b805397fc
ROOST_METHOD_SIG_HASH=equals_f2d574000d

Scenario 1: Verify equality when comparing the same object instance.
Details:
  TestName: equalsSameObjectInstance
  Description: Ensure that the `equals()` method returns `true` when the compared object is the same instance as the calling object. This verifies the `this == o` condition in the code.
Execution:
  Arrange: Create an instance of the `Attribute` class.
  Act: Pass the same instance to the `equals()` method.
  Assert: Assert that the method returns `true`.
Validation:
  This test ensures that object identity is correctly handled by the `equals()` method. If two references point to the same object, equality should return `true`.
---
Scenario 2: Verify inequality when compared with `null`.
Details:
  TestName: equalsWithNull
  Description: Test the behavior of the `equals()` method when comparing the object with a `null` reference. This checks the `o == null` condition in the code.
Execution:
  Arrange: Create an instance of the `Attribute` class.
  Act: Pass `null` to the `equals()` method.
  Assert: Assert that the method returns `false`.
Validation:
  This test confirms that the method correctly returns `false` for null comparisons, as null cannot be equal to any object.
---
Scenario 3: Verify inequality when comparing objects of different classes.
Details:
  TestName: equalsWithDifferentClassObject
  Description: Validate that the `equals()` method returns `false` if the compared object belongs to a different class. This tests the `getClass() != o.getClass()` condition in the code.
Execution:
  Arrange: Create an instance of the `Attribute` class, and another instance of a different class (e.g., `String`).
  Act: Pass the instance of the different class to the `equals()` method.
  Assert: Assert that the method returns `false`.
Validation:
  This test ensures type safety in comparisons by verifying that objects of different classes are not considered equal.
---
Scenario 4: Verify equality for objects with the same values for `name`, `value`, and `type`.
Details:
  TestName: equalsWithSameValues
  Description: Test that two `Attribute` objects with identical values for the fields `name`, `value`, and `type` are considered equal.
Execution:
  Arrange: Create two instances of the `Attribute` class with identical values for `name`, `value`, and `type`.
  Act: Compare the two instances using the `equals()` method.
  Assert: Assert that the method returns `true`.
Validation:
  This test ensures that the `equals()` method correctly evaluates equality based on the object's content rather than its reference.
---
Scenario 5: Verify inequality for objects with different values for the `name` field.
Details:
  TestName: equalsWithDifferentName
  Description: Test that two `Attribute` objects with differing values for the `name` field are not considered equal.
Execution:
  Arrange: Create two instances of the `Attribute` class. Set identical values for `value` and `type` fields, but assign different values for the `name` field.
  Act: Compare the two instances using the `equals()` method.
  Assert: Assert that the method returns `false`.
Validation:
  This test ensures that the `name` field is correctly considered in the equality logic and changes in its value result in inequality.
---
Scenario 6: Verify inequality for objects with different values for the `value` field.
Details:
  TestName: equalsWithDifferentValue
  Description: Test that two `Attribute` objects with differing values for the `value` field are not considered equal.
Execution:
  Arrange: Create two instances of the `Attribute` class. Set identical values for `name` and `type` fields, but assign different values for the `value` field.
  Act: Compare the two instances using the `equals()` method.
  Assert: Assert that the method returns `false`.
Validation:
  This test ensures that the `value` field is correctly considered in the equality logic and changes in its value result in inequality.
---
Scenario 7: Verify inequality for objects with different values for the `type` field.
Details:
  TestName: equalsWithDifferentType
  Description: Test that two `Attribute` objects with differing values for the `type` field are not considered equal.
Execution:
  Arrange: Create two instances of the `Attribute` class. Set identical values for `name` and `value` fields, but assign different values for the `type` field.
  Act: Compare the two instances using the `equals()` method.
  Assert: Assert that the method returns `false`.
Validation:
  This test ensures that the `type` field is correctly accounted for in the equality logic and changes in its value result in inequality.
---
Scenario 8: Verify behavior when all fields (`name`, `value`, `type`) are `null`.
Details:
  TestName: equalsWithAllFieldsNull
  Description: Test that two `Attribute` objects with all fields (`name`, `value`, `type`) set to `null` are considered equal.
Execution:
  Arrange: Create two instances of the `Attribute` class, ensure all fields are explicitly set to `null`.
  Act: Compare the two instances using the `equals()` method.
  Assert: Assert that the method returns `true`.
Validation:
  This test ensures that `Objects.equals()` operates correctly when comparing null values and confirms that the equality logic allows for both objects having null fields.
---
Scenario 9: Verify behavior when one field is `null` and the other has a non-null value.
Details:
  TestName: equalsWithOneFieldNullAndOtherNonNull
  Description: Validate that two `Attribute` objects are not equal if one has a field set to `null` while the other has a non-null value for the same field.
Execution:
  Arrange: Create two instances of the `Attribute` class. Ensure one object has `null` for a specific field while another object has a non-null value for the same field.
  Act: Compare the two instances using the `equals()` method.
  Assert: Assert that the method returns `false`.
Validation:
  This test ensures that fields set to null are correctly distinguished from non-null fields during equality comparison.
---
Scenario 10: Verify transitivity of the `equals()` method.
Details:
  TestName: equalsTransitivityCheck
  Description: Test that equality is transitive by verifying that if `A.equals(B)` and `B.equals(C)`, then `A.equals(C)` is also `true`.
Execution:
  Arrange: Create three instances of the `Attribute` class, all with identical values for `name`, `value`, and `type`.
  Act: Compare `A` with `B`, `B` with `C`, and then `A` with `C` using the `equals()` method.
  Assert: Assert that all comparisons return `true`.
Validation:
  This test ensures that the `equals()` method adheres to the transitivity property of equivalence relations.
*/
// ********RoostGPT********
package io.spring.initializr.generator.buildsystem.gradle;

import java.util.Objects;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;
import org.junit.jupiter.api.*;

@Tag("io.spring.initializr.generator.buildsystem.gradle")
@Tag("io.spring.initializr.generator.buildsystem.gradle.equals")
class AttributeEqualsTest {

	public enum Type {

		TYPE_A, TYPE_B

	}

	@Test
	@Tag("valid")
	void equalsSameObjectInstance() {
		Attribute attribute = new Attribute("TestName", "TestValue", Type.TYPE_A);
		assertThat(attribute.equals(attribute)).isTrue();
	}

	@Test
	@Tag("invalid")
	void equalsWithNull() {
		Attribute attribute = new Attribute("TestName", "TestValue", Type.TYPE_A);
		assertThat(attribute.equals(null)).isFalse();
	}

	@Test
	@Tag("invalid")
	void equalsWithDifferentClassObject() {
		Attribute attribute = new Attribute("TestName", "TestValue", Type.TYPE_A);
		String otherObject = "RandomString";
		assertThat(attribute.equals(otherObject)).isFalse();
	}

	@Test
	@Tag("valid")
	void equalsWithSameValues() {
		Attribute attribute1 = new Attribute("TestName", "TestValue", Type.TYPE_A);
		Attribute attribute2 = new Attribute("TestName", "TestValue", Type.TYPE_A);
		assertThat(attribute1.equals(attribute2)).isTrue();
	}

	@Test
	@Tag("invalid")
	void equalsWithDifferentName() {
		Attribute attribute1 = new Attribute("TestName1", "TestValue", Type.TYPE_A);
		Attribute attribute2 = new Attribute("TestName2", "TestValue", Type.TYPE_A);
		assertThat(attribute1.equals(attribute2)).isFalse();
	}

	@Test
	@Tag("invalid")
	void equalsWithDifferentValue() {
		Attribute attribute1 = new Attribute("TestName", "TestValue1", Type.TYPE_A);
		Attribute attribute2 = new Attribute("TestName", "TestValue2", Type.TYPE_A);
		assertThat(attribute1.equals(attribute2)).isFalse();
	}

	@Test
	@Tag("invalid")
	void equalsWithDifferentType() {
		Attribute attribute1 = new Attribute("TestName", "TestValue", Type.TYPE_A);
		Attribute attribute2 = new Attribute("TestName", "TestValue", Type.TYPE_B);
		assertThat(attribute1.equals(attribute2)).isFalse();
	}

	@Test
	@Tag("boundary")
	void equalsWithAllFieldsNull() {
		Attribute attribute1 = new Attribute(null, null, null);
		Attribute attribute2 = new Attribute(null, null, null);
		assertThat(attribute1.equals(attribute2)).isTrue();
	}

	@Test
	@Tag("boundary")
	void equalsWithOneFieldNullAndOtherNonNull() {
		Attribute attribute1 = new Attribute(null, "TestValue", Type.TYPE_A);
		Attribute attribute2 = new Attribute("TestName", "TestValue", Type.TYPE_A);
		assertThat(attribute1.equals(attribute2)).isFalse();
	}

	@Test
	@Tag("valid")
	void equalsTransitivityCheck() {
		Attribute attributeA = new Attribute("TestName", "TestValue", Type.TYPE_A);
		Attribute attributeB = new Attribute("TestName", "TestValue", Type.TYPE_A);
		Attribute attributeC = new Attribute("TestName", "TestValue", Type.TYPE_A);
		boolean isABEqual = attributeA.equals(attributeB);
		boolean isBCEqual = attributeB.equals(attributeC);
		boolean isACEqual = attributeA.equals(attributeC);
		assertThat(isABEqual && isBCEqual && isACEqual).isTrue();
	}

}