/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
ROOST_METHOD_HASH=add_132109175b
ROOST_METHOD_SIG_HASH=add_97d1c992b1
Scenario 1: Verify that a plugin is correctly added to the `plugins` map when the method `add(String id)` is invoked.
Details:
  TestName: addPluginSuccessfullyWithIdOnly
  Description: This test verifies that invoking the `add(String id)` method adds a new plugin to the `plugins` map with the specified ID as the key and a `StandardGradlePlugin` as the value. It ensures that the plugin is properly initialized and stored within the `plugins` map.
Execution:
  Arrange: Create an instance of `GradlePluginContainer`. Prepare a valid plugin ID as input.
  Act: Call the `add(String id)` method using the prepared plugin ID.
  Assert: Verify that the `plugins` map contains the key corresponding to the provided ID and that the associated value is an instance of `StandardGradlePlugin`.
Validation:
  The test ensures that the `add(String id)` method adds a plugin correctly and validates that the `StandardGradlePlugin` instance is stored in the map as expected. This test is significant in confirming the core functionality of the `add` method.
---
Scenario 2: Verify handling of duplicate plugin IDs passed to the `add(String id)` method.
Details:
  TestName: preventDuplicatePluginIds
  Description: This test checks the behavior when the method `add(String id)` is invoked with a duplicate plugin ID. It ensures that duplicate keys are not added to the `plugins` map and that the original plugin value remains unchanged.
Execution:
  Arrange: Create an instance of `GradlePluginContainer`. Add a plugin with an initial ID to the `plugins` map. Reuse the same plugin ID for the `add(String id)` method call.
  Act: Invoke the `add(String id)` method with the duplicate plugin ID.
  Assert: Verify that the `plugins` map still contains the original value associated with the duplicate ID and did not add a new entry.
Validation:
  The test ensures that the `add` method safeguards against replacing an existing plugin with the same ID, preserving the integrity of the `plugins` map.
---
Scenario 3: Validate behavior when an empty string is passed as the ID to the `add(String id)` method.
Details:
  TestName: handleEmptyStringPluginId
  Description: This test examines the behavior of the `add(String id)` method when an empty string is used as the plugin ID. It ensures that the method does not inadvertently add entries with invalid IDs to the `plugins` map.
Execution:
  Arrange: Create an instance of `GradlePluginContainer`. Pass an empty string (`""`) as the plugin ID.
  Act: Invoke the `add(String id)` method with the empty string.
  Assert: Verify that the `plugins` map does not contain any key or value associated with the empty string.
Validation:
  This test safeguards against invalid input scenarios, ensuring that entries with empty or unsuitable IDs are not added to the `plugins` map.
---
Scenario 4: Validate behavior when `null` is passed as the ID to the `add(String id)` method.
Details:
  TestName: handleNullPluginId
  Description: This test checks how the `add(String id)` method behaves when `null` is supplied as the plugin ID. It ensures that the method does not inadvertently add a `null` key or throw unexpected exceptions.
Execution:
  Arrange: Create an instance of `GradlePluginContainer`. Pass `null` as the plugin ID.
  Act: Invoke the `add(String id)` method with the `null` value.
  Assert: Verify that the `plugins` map does not contain any key or value associated with `null`.
Validation:
  The test ensures robust handling of `null` inputs, confirming that the method does not modify the `plugins` map or fail due to null values.
---
Scenario 5: Verify compatibility with multiple valid plugin IDs added sequentially using the `add(String id)` method.
Details:
  TestName: addMultiplePluginsSuccessfully
  Description: This test ensures that the `add(String id)` method allows sequential addition of plugins with unique IDs and correctly updates the `plugins` map for each addition.
Execution:
  Arrange: Create an instance of `GradlePluginContainer`. Prepare a list of unique valid plugin IDs.
  Act: Invoke the `add(String id)` method multiple times using each ID in the list.
  Assert: Verify that the `plugins` map contains keys corresponding to all IDs and that each value is an instance of `StandardGradlePlugin`.
Validation:
  The test ensures the cumulative correctness and flexibility of the `add` method, confirming that multiple plugins can be added without conflict.
---
Scenario 6: Verify handling of invalid plugin IDs such as whitespace-only strings passed to the `add(String id)` method.
Details:
  TestName: rejectWhitespaceStringPluginId
  Description: This test examines the behavior of the `add(String id)` method when a whitespace-only string is provided as the plugin ID. It validates that such inputs are disregarded and do not alter the `plugins` map.
Execution:
  Arrange: Create an instance of `GradlePluginContainer`. Prepare a whitespace-only string (`"   "`) as the plugin ID.
  Act: Invoke the `add(String id)` method with the whitespace-only string.
  Assert: Verify that the `plugins` map does not contain any key or value associated with the whitespace string.
Validation:
  This test discourages invalid entries caused by whitespace strings, securing the integrity of the `plugins` map.
---
Scenario 7: Validate that the `add(String id)` method initializes the `StandardGradlePlugin` with the correct structure.
Details:
  TestName: checkStandardGradlePluginInitialization
  Description: This test confirms that invoking the `add(String id)` method results in the creation of a properly initialized `StandardGradlePlugin` instance that adheres to expected defaults.
Execution:
  Arrange: Create an instance of `GradlePluginContainer`. Provide a valid plugin ID with expected initialization properties.
  Act: Call the `add(String id)` method with the valid ID.
  Assert: Verify that the associated value in the `plugins` map is a properly initialized `StandardGradlePlugin`.
Validation:
  The test ensures the correctness of plugin initialization during the `add` process, validating the expected structure of the `StandardGradlePlugin` instance.
*/
// ********RoostGPT********
package io.spring.initializr.generator.buildsystem.gradle;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;
import java.util.LinkedHashMap;
import org.junit.jupiter.api.*;
import java.util.Map;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.stream.Stream;
import org.junit.jupiter.api.*;

@Tag("io.spring.initializr.generator.buildsystem.gradle")
@Tag("io.spring.initializr.generator.buildsystem.gradle.add")
class GradlePluginContainerAddTest {

	private static class GradlePluginContainer {

		private final LinkedHashMap<String, GradlePlugin> plugins = new LinkedHashMap<>();

		public void add(String id) {
			addPlugin(id, StandardGradlePlugin::new);
		}

		private GradlePlugin addPlugin(String id, Function<String, GradlePlugin> pluginFactory) {
			return plugins.computeIfAbsent(id, pluginFactory);
		}

	}

	@Test
	@Tag("valid")
	public void addPluginSuccessfullyWithIdOnly() {
		GradlePluginContainer container = new GradlePluginContainer();
		String pluginId = "com.example.plugin"; // TODO: Update pluginId if necessary

		container.add(pluginId);
		GradlePlugin plugin = container.plugins.get(pluginId);
		assertThat(plugin).isInstanceOf(StandardGradlePlugin.class);
		assertThat(plugin.getId()).isEqualTo(pluginId);
	}

	@Test
	@Tag("boundary")
	public void preventDuplicatePluginIds() {
		GradlePluginContainer container = new GradlePluginContainer();
		String pluginId = "com.example.plugin"; // TODO: Update pluginId if necessary

		container.add(pluginId);
		GradlePlugin originalPlugin = container.plugins.get(pluginId);
		container.add(pluginId);

		GradlePlugin plugin = container.plugins.get(pluginId);
		assertThat(plugin).isSameAs(originalPlugin);
	}

	@Test
	@Tag("invalid")
	public void handleEmptyStringPluginId() {
		GradlePluginContainer container = new GradlePluginContainer();
		String pluginId = ""; // An empty string ID

		container.add(pluginId);
		assertThat(container.plugins.containsKey(pluginId)).isFalse();
	}

	@Test
	@Tag("invalid")
	public void handleNullPluginId() {
		GradlePluginContainer container = new GradlePluginContainer();
		String pluginId = null; // A null ID
		container.add(pluginId);
		assertThat(container.plugins.containsKey(pluginId)).isFalse();
	}

	@Test
	@Tag("valid")
	public void addMultiplePluginsSuccessfully() {
		GradlePluginContainer container = new GradlePluginContainer();
		String[] pluginIds = { "com.example.plugin1", "com.example.plugin2", "com.example.plugin3" };
		for (String pluginId : pluginIds) {
			container.add(pluginId);
			GradlePlugin plugin = container.plugins.get(pluginId);
			assertThat(plugin).isInstanceOf(StandardGradlePlugin.class);
			assertThat(plugin.getId()).isEqualTo(pluginId);
		}
		assertThat(container.plugins.keySet()).containsExactly(pluginIds);
	}

	@Test
	@Tag("invalid")
	public void rejectWhitespaceStringPluginId() {
		GradlePluginContainer container = new GradlePluginContainer();
		String pluginId = "    "; // A string with only whitespace

		container.add(pluginId);
		assertThat(container.plugins.containsKey(pluginId.trim())).isFalse();
	}

	@Test
	@Tag("valid")
	public void checkStandardGradlePluginInitialization() {
		GradlePluginContainer container = new GradlePluginContainer();
		String pluginId = "com.example.plugin"; // TODO: Update pluginId if necessary
		container.add(pluginId);

		GradlePlugin plugin = container.plugins.get(pluginId);
		assertThat(plugin).isInstanceOf(StandardGradlePlugin.class);
		StandardGradlePlugin standardPlugin = (StandardGradlePlugin) plugin;
		assertThat(standardPlugin.getVersion()).isNull();
	}

}