/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
ROOST_METHOD_HASH=add_2b53e280ca
ROOST_METHOD_SIG_HASH=add_f3bf9aa0c5

Scenario 1: Test Addition of Valid Plugin with Consumer
Details:
  TestName: addValidPluginAndConsume
  Description: This test ensures that a plugin added with a valid ID and a Consumer function correctly invokes the Consumer if the plugin is of type StandardGradlePlugin.
Execution:
  Arrange: Set up a valid plugin ID and a Consumer that asserts the valid interaction with a StandardGradlePlugin instance.
  Act: Call the `add` method with the provided ID and Consumer.
  Assert: Verify that the Consumer was called exactly once and interacted correctly with the StandardGradlePlugin instance.
Validation:
  Verify that plugins can be added and consumed with the intended functionality. This confirms the method correctly checks the plugin type and calls the Consumer on the matching instance.
*/
// ********RoostGPT********
package io.spring.initializr.generator.buildsystem.gradle;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import java.util.function.Consumer;
import static org.mockito.Mockito.*;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import org.springframework.util.Assert;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Stream;
import org.junit.jupiter.api.*;

@Tag("io.spring.initializr.generator.buildsystem.gradle")
@Tag("io.spring.initializr.generator.buildsystem.gradle.add")
class GradlePluginContainerAdd801Test {

	@Test
	@Tag("valid")
	void addValidPluginAndConsume() {
		// Arrange
		GradlePluginContainer container = new GradlePluginContainer();
		String validPluginId = "com.example.validPlugin";
		Consumer<StandardGradlePlugin> mockConsumer = mock(Consumer.class);
		// Act
		container.add(validPluginId, mockConsumer);
		// Assert
		verify(mockConsumer, times(1)).accept(Mockito.argThat(plugin -> validPluginId.equals(plugin.getId())));
	}

	@Test
	@Tag("boundary")
	void addBoundaryCasePluginId() {
		// Update this test to handle the boundary case where an empty plugin ID is
		// supplied
		// This test expects that the plugin ID cannot be empty or null. If empty plugin
		// ID is invalid,
		// the associated business logic (`add` method) should enforce validation for
		// non-empty plugin ID.
		// Arrange
		GradlePluginContainer container = new GradlePluginContainer();
		String boundaryPluginId = "";
		Consumer<StandardGradlePlugin> mockConsumer = mock(Consumer.class);
		// Business Logic Enhancement Suggestion: Ensure "id" is validated as non-empty in
		// the `add` method.
		// Act & Assert
		container.add(boundaryPluginId, plugin -> Assert.state(boundaryPluginId != null && !boundaryPluginId.isEmpty(),
				"Plugin ID should not be empty."));
		verify(mockConsumer, times(1)).accept(Mockito.argThat(plugin -> boundaryPluginId.equals(plugin.getId())));
	}

	@Test
	@Tag("invalid")
	void addInvalidPluginType() {
		// Arrange
		GradlePluginContainer container = new GradlePluginContainer();
		String invalidPluginId = null; // Invalid as ID is null
		Consumer<StandardGradlePlugin> mockConsumer = mock(Consumer.class);
		// Act & Assert for Null ID
		assertThatThrownBy(() -> container.add(invalidPluginId, mockConsumer)).isInstanceOf(NullPointerException.class)
			.hasMessageContaining("id is marked non-null but is null");
	}

	@Test
	@Tag("integration")
	void addIntegrationTestForPluginApplication() {
		// Arrange
		GradlePluginContainer container = new GradlePluginContainer();
		String pluginId = "com.example.integrationPlugin";
		Consumer<StandardGradlePlugin> mockConsumer = mock(Consumer.class);
		// Act
		container.add(pluginId, mockConsumer);
		// Assert
		verify(mockConsumer, times(1)).accept(Mockito.argThat(plugin -> pluginId.equals(plugin.getId())));
	}

}