/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_2b53e280ca
ROOST_METHOD_SIG_HASH=add_3bb4084527


Scenario [1]: Add a plugin with valid ID and verify its existence in the plugin map

Details:
  TestName: addStandardPluginWithConsumer
  Description: Check if a plugin with a specified ID is correctly added to the internal map and the supplied consumer is applied when the plugin is of type `StandardGradlePlugin`.

Execution:
  Arrange:
    - Create an instance of `GradlePluginContainer`.
    - Define a valid plugin ID (`"test-plugin"`).
    - Define a consumer that alters a property or performs an action on a `StandardGradlePlugin` instance.

  Act:
    - Call `add("test-plugin", consumer)` on the container instance.

  Assert:
    - Verify that the internal map (`plugins`) contains an entry with the given ID (`"test-plugin"`).

Validation:
  - The assertion ensures that the `add` method correctly adds the plugin to the map and invokes the provided consumer if the plugin instance is a `StandardGradlePlugin`.
  - This test validates the default flow where a valid plugin is added successfully.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem.gradle;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import java.util.function.Consumer;
import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Stream;

class GradlePluginContainerAdd986Test {

	@Test
	@Tag("valid")
	public void addStandardPluginWithConsumer() {
		// Arrange
		GradlePluginContainer container = new GradlePluginContainer();
		String pluginId = "test-plugin";
		Consumer<StandardGradlePlugin> consumer = mock(Consumer.class);
		// Act
		container.add(pluginId, consumer);
		// Assert
		GradlePlugin addedPlugin = container.getPlugin(pluginId);
		assertThat(addedPlugin).isNotNull();
		assertThat(addedPlugin.getId()).isEqualTo(pluginId);
		assertThat(addedPlugin instanceof StandardGradlePlugin).isTrue();
		verify(consumer).accept((StandardGradlePlugin) addedPlugin);
	}

	@Test
	@Tag("invalid")
	public void addNullPluginIdWithConsumer() {
		// Arrange
		GradlePluginContainer container = new GradlePluginContainer();
		Consumer<StandardGradlePlugin> consumer = mock(Consumer.class);
		// Act & Assert
		try {
			container.add(null, consumer); // TODO: Ensure null value behavior is defined
											// in implementation
		}
		catch (IllegalArgumentException ex) {
			assertThat(ex).hasMessage("Plugin id must not be null");
		}
	}

	@Test
	@Tag("boundary")
	public void addEmptyPluginIdWithConsumer() {
		// Arrange
		GradlePluginContainer container = new GradlePluginContainer();
		String pluginId = ""; // TODO: Verify empty string is valid or defined as invalid
								// scenario
		Consumer<StandardGradlePlugin> consumer = mock(Consumer.class);
		// Act
		container.add(pluginId, consumer);
		// Assert
		GradlePlugin addedPlugin = container.getPlugin(pluginId);
		assertThat(addedPlugin).isNotNull();
		assertThat(addedPlugin.getId()).isEqualTo(pluginId);
		assertThat(addedPlugin instanceof StandardGradlePlugin).isTrue();
		verify(consumer).accept((StandardGradlePlugin) addedPlugin);
	}

	@Test
	@Tag("valid")
	public void addPluginVerifyConsumerIgnoresStandardPlugin() {
		// Arrange
		GradlePluginContainer container = new GradlePluginContainer();
		String pluginId = "mock-plugin";
		Consumer<StandardGradlePlugin> consumer = mock(Consumer.class);
		// Act
		GradlePlugin gradlePlugin = container.addPlugin(pluginId, GradlePlugin::new);
		assertThat(gradlePlugin instanceof StandardGradlePlugin).isFalse();
		// Assert
		container.add(pluginId, consumer);
		verifyNoInteractions(consumer); // Ensure consumer is untouched
	}

}