/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_2b53e280ca
ROOST_METHOD_SIG_HASH=add_3bb4084527


Scenario 1: Test Addition of Valid Plugin with Consumer

Details:
  TestName: addValidPluginAndConsume
  Description: This test ensures that a plugin added with a valid ID and a Consumer function correctly invokes the Consumer if the plugin is of type StandardGradlePlugin.

Execution:
  Arrange: Set up a valid plugin ID and a Consumer that asserts the valid interaction with a StandardGradlePlugin instance.
  Act: Call the `add` method with the provided ID and Consumer.
  Assert: Verify that the Consumer was called exactly once and interacted correctly with the StandardGradlePlugin instance.

Validation:
  Verify that plugins can be added and consumed with the intended functionality. This confirms the method correctly checks the plugin type and calls the Consumer on the matching instance.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem.gradle;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import java.util.function.Consumer;
import static org.mockito.Mockito.*;
import static org.assertj.core.api.Assertions.assertThat;
import org.junit.jupiter.api.*;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Stream;

class GradlePluginContainerAdd809Test {

	@Test
	@Tag("valid")
	public void addValidPluginAndConsume() {
		// Arrange
		GradlePluginContainer gradlePluginContainer = Mockito.spy(new GradlePluginContainer());
		String validPluginId = "examplePlugin"; // TODO: Replace with actual plugin ID for
												// testing
		Consumer<StandardGradlePlugin> consumer = Mockito.mock(Consumer.class);
		// Act
		Mockito.doReturn(new StandardGradlePlugin(validPluginId))
			.when(gradlePluginContainer)
			.addPlugin(validPluginId, StandardGradlePlugin::new);
		gradlePluginContainer.add(validPluginId, consumer);
		// Assert
		verify(consumer).accept(any(StandardGradlePlugin.class)); // Ensure consumer was
																	// called
	}

	@Test
	@Tag("invalid")
	public void addInvalidPluginDoesNotConsume() {
		// Arrange
		GradlePluginContainer gradlePluginContainer = Mockito.spy(new GradlePluginContainer());
		String invalidPluginId = "invalidPlugin";
		Consumer<StandardGradlePlugin> consumer = Mockito.mock(Consumer.class);
		// Act
		Mockito.doReturn(new GradlePlugin(invalidPluginId, false))
			.when(gradlePluginContainer)
			.addPlugin(invalidPluginId, StandardGradlePlugin::new);
		gradlePluginContainer.add(invalidPluginId, consumer);
		// Assert
		verify(consumer, never()).accept(any(StandardGradlePlugin.class)); // Ensure
																			// consumer
																			// was not
																			// called
	}

	@Test
	@Tag("boundary")
	public void addPluginHandlesNullConsumerGracefully() {
		// Arrange
		GradlePluginContainer gradlePluginContainer = Mockito.spy(new GradlePluginContainer());
		String pluginId = "boundaryPlugin";
		// Act
		Mockito.doReturn(new StandardGradlePlugin(pluginId))
			.when(gradlePluginContainer)
			.addPlugin(pluginId, StandardGradlePlugin::new);
		gradlePluginContainer.add(pluginId, null);
		// Assert
		// Ensure no exception is thrown and no interaction happens
		verifyNoInteractions(gradlePluginContainer);
	}

	@Test
	@Tag("boundary")
	public void addPluginHandlesEmptyPluginId() {
		// Arrange
		GradlePluginContainer gradlePluginContainer = Mockito.spy(new GradlePluginContainer());
		String emptyPluginId = ""; // TODO: Test with empty identifier
		Consumer<StandardGradlePlugin> consumer = Mockito.mock(Consumer.class);
		// Act
		Mockito.doReturn(new StandardGradlePlugin(emptyPluginId))
			.when(gradlePluginContainer)
			.addPlugin(emptyPluginId, StandardGradlePlugin::new);
		gradlePluginContainer.add(emptyPluginId, consumer);
		// Assert
		verify(consumer).accept(any(StandardGradlePlugin.class)); // Ensure consumer was
																	// called
	}

	@Test
	@Tag("integration")
	public void addPluginIntegrationValidScenario() {
		// Arrange
		GradlePluginContainer gradlePluginContainer = Mockito.spy(new GradlePluginContainer());
		String pluginId = "integrationPlugin"; // TODO: Replace with actual plugin ID for
												// integration testing
		Consumer<StandardGradlePlugin> consumer = plugin -> assertThat(plugin.getVersion()).isNotNull(); // Verify
																											// plugin's
																											// attributes
		// Act
		Mockito.doReturn(new StandardGradlePlugin(pluginId))
			.when(gradlePluginContainer)
			.addPlugin(pluginId, StandardGradlePlugin::new);
		gradlePluginContainer.add(pluginId, consumer);
		// Assert
		// Consumer should successfully validate non-null version or attributes
	}

}