/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_2b53e280ca
ROOST_METHOD_SIG_HASH=add_3bb4084527


Scenario 1: Test Addition of Valid Plugin with Consumer

Details:
  TestName: addValidPluginAndConsume
  Description: This test ensures that a plugin added with a valid ID and a Consumer function correctly invokes the Consumer if the plugin is of type StandardGradlePlugin.

Execution:
  Arrange: Set up a valid plugin ID and a Consumer that asserts the valid interaction with a StandardGradlePlugin instance.
  Act: Call the `add` method with the provided ID and Consumer.
  Assert: Verify that the Consumer was called exactly once and interacted correctly with the StandardGradlePlugin instance.

Validation:
  Verify that plugins can be added and consumed with the intended functionality. This confirms the method correctly checks the plugin type and calls the Consumer on the matching instance.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem.gradle;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import org.mockito.ArgumentCaptor;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.stream.Stream;

class GradlePluginContainerAdd749Test {

	@Test
	@Tag("valid")
	void addValidPluginAndConsume() {
		// Arrange
		GradlePluginContainer gradlePluginContainer = new GradlePluginContainer();
		String validPluginId = "validPluginId";
		Consumer<StandardGradlePlugin> mockConsumer = Mockito.mock(Consumer.class);
		// Act
		gradlePluginContainer.add(validPluginId, mockConsumer);
		// Assert
		ArgumentCaptor<StandardGradlePlugin> argumentCaptor = ArgumentCaptor.forClass(StandardGradlePlugin.class);
		Mockito.verify(mockConsumer, Mockito.times(1)).accept(argumentCaptor.capture());
		StandardGradlePlugin capturedPlugin = argumentCaptor.getValue();
		assert capturedPlugin != null : "Captured plugin should not be null";
		assert capturedPlugin instanceof StandardGradlePlugin
				: "Captured plugin should be instance of StandardGradlePlugin";
		assert capturedPlugin.getVersion() == null : "Initially, version should be null as it's not set";
		assert validPluginId.equals(((GradlePlugin) capturedPlugin).getId())
				: "Plugin ID should match the expected value";
	}

}