/*
 * Copyright 2012-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-filter-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_2b53e280ca
ROOST_METHOD_SIG_HASH=add_3bb4084527


Scenario 1: Test Addition of Valid Plugin with Consumer

Details:
  TestName: addValidPluginAndConsume
  Description: This test ensures that a plugin added with a valid ID and a Consumer function correctly invokes the Consumer if the plugin is of type StandardGradlePlugin.

Execution:
  Arrange: Set up a valid plugin ID and a Consumer that asserts the valid interaction with a StandardGradlePlugin instance.
  Act: Call the `add` method with the provided ID and Consumer.
  Assert: Verify that the Consumer was called exactly once and interacted correctly with the StandardGradlePlugin instance.

Validation:
  Verify that plugins can be added and consumed with the intended functionality. This confirms the method correctly checks the plugin type and calls the Consumer on the matching instance.

*/

// ********RoostGPT********

package io.spring.initializr.generator.buildsystem.gradle;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.Mockito;
import java.util.function.Consumer;
import org.junit.jupiter.api.*;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Stream;

@Tag("integration")
public class GradlePluginContainerAdd425Test {

	GradlePluginContainer gradlePluginContainer = new GradlePluginContainer(); // Instantiate
																				// the
																				// class
																				// under
																				// test

	@Test
	@Tag("valid")
	public void addValidPluginAndConsume() {
		// Arrange
		String validPluginId = "com.example.plugin"; // TODO: Adjust plugin ID if
														// necessary
		Consumer<StandardGradlePlugin> mockConsumer = Mockito.mock(Consumer.class);
		// Act
		gradlePluginContainer.add(validPluginId, mockConsumer);
		// Assert
		Mockito.verify(mockConsumer, Mockito.times(1)).accept(Mockito.any(StandardGradlePlugin.class));
	}

	@Test
	@Tag("invalid")
	public void addPluginWithNullId() {
		// Arrange
		Consumer<StandardGradlePlugin> mockConsumer = Mockito.mock(Consumer.class);
		// Act & Assert
		try {
			gradlePluginContainer.add(null, mockConsumer);
			throw new AssertionError("Expected an IllegalArgumentException");
		}
		catch (IllegalArgumentException e) {
			// Verify exception scenario
		}
	}

	@Test
	@Tag("invalid")
	public void addPluginWithEmptyId() {
		// Arrange
		String emptyPluginId = ""; // TODO: Adjust if method implementation changes
		Consumer<StandardGradlePlugin> mockConsumer = Mockito.mock(Consumer.class);
		// Act & Assert
		try {
			gradlePluginContainer.add(emptyPluginId, mockConsumer);
			throw new AssertionError("Expected an IllegalArgumentException");
		}
		catch (IllegalArgumentException e) {
			// Verify exception scenario
		}
	}

	@Test
	@Tag("boundary")
	public void addPluginWithLongId() {
		// Arrange
		String longPluginId = "a".repeat(1024); // A very large string, may need
												// adjustment
		Consumer<StandardGradlePlugin> mockConsumer = Mockito.mock(Consumer.class);
		// Act
		gradlePluginContainer.add(longPluginId, mockConsumer);
		// Assert
		Mockito.verify(mockConsumer, Mockito.times(1)).accept(Mockito.any(StandardGradlePlugin.class));
	}

	@Test
	@Tag("valid")
	public void addValidPluginWithoutConsumerTrigger() {
		// Arrange
		String validPluginId = "com.example.simpleplugin";
		// Act
		gradlePluginContainer.add(validPluginId, null);
		// Assert
		// Verify no exception was thrown (valid scenario with null consumer)
	}

}